// PyMasters v3 - Course Data (Full Rewrite)
const COURSES = [
// ========== 1. Pythonをはじめよう ==========
{id:"py-start",title:"Pythonをはじめよう",desc:"プログラミングの世界へ最初の一歩。何も知らなくて大丈夫！",level:"b",icon:"🌱",free:true,nextCourse:"py-basics",lessons:[
{id:"s1",title:"プログラミングって何？",xp:30,
content:[{type:"text",body:"## プログラミングって何だろう？🤔\n\n想像してみて。友達に「コンビニでおにぎり買ってきて」って頼むとき、人間なら「OK！」で通じるよね。\n\nでもコンピュータは**超マジメ**だから、こう言わないと動かない：\n\n1. コンビニまで歩く\n2. おにぎりコーナーに行く\n3. ツナマヨを1つ取る\n4. レジに持っていく\n5. 支払う\n\nこうやって**やることを順番に、具体的に書く**のがプログラミング！"},{type:"text",body:"### なんでPythonなの？\n\nプログラミング言語はたくさんあるけど、Pythonは**世界で一番人気**の言語のひとつ。\n\n人気の理由はシンプル：\n- 📖 **読みやすい** → 英語に近くて、初めてでもなんとなく読める\n- 🛠️ **なんでもできる** → AI、Webサイト、データ分析、ゲーム…\n- 🌍 **仲間が多い** → 困ったらネットで日本語の情報がたくさん見つかる"},{type:"tip",body:"💡 このアプリでは何もインストールしなくてOK！ ブラウザの中でPythonが動くから、右のエディタにコードを書いてすぐ試せるよ！"}],exercise:{instruction:"右のエディタに以下のコードを書いて、Enterキーで実行してみましょう！\nprint(\"プログラミング、楽しそう！\")",initialCode:"# ここにコードを書いてね！\n",expectedOutput:"プログラミング、楽しそう！",keywords:["print"],answer:"print(\"プログラミング、楽しそう！\")",hints:["print() という命令を使います","カッコの中に表示したい文字を書きます","print(\"プログラミング、楽しそう！\") と書いてみてください"]}},
{id:"s2",title:"画面に文字を表示しよう - print文",xp:40,
content:[{type:"text",body:"## <span class=\"term\" data-term=\"print\">print文</span>を覚えよう！📢\n\nPythonで最初に覚える命令は <span class=\"term\" data-term=\"print\">print()</span>。\n\nこれは「カッコの中身を画面に表示してね」っていう命令だよ。"},{type:"code",code:"print(\"こんにちは！\")",desc:"これだけ！カッコの中に表示したいものを書く"},{type:"text",body:"### 書き方のルール\n\n文字を表示するには **\" \"（ダブルクォート）** か **' '（シングルクォート）** で囲む：\n\n<span class=\"copyable\">print(\"こんにちは\")</span> → OK ✅\n<span class=\"copyable\">print('こんにちは')</span> → OK ✅（どっちでも同じ！）\n\n数字はクォートなしでOK：\n\n<span class=\"copyable\">print(42)</span> → 数字の42\n<span class=\"copyable\">print(\"42\")</span> → 文字としての42（今は同じに見えるけど、計算のとき大違い！）"},{type:"tip",body:"💡 **よくあるミス TOP3：**\n① `pritn` → スペルミス！ `print` だよ\n② `print \"hello\"` → カッコ `()` 忘れ！\n③ `print(hello)` → クォート忘れ！文字は `\"hello\"` って囲むこと"}],exercise:{instruction:"3行で表示してください。\n1行目: 「Python」\n2行目: 「は」\n3行目: 「楽しい！」",initialCode:"# 3つのprint文を書いてね\n",expectedOutput:"Python\nは\n楽しい！",keywords:["print"],answer:"print(\"Python\")\nprint(\"は\")\nprint(\"楽しい！\")",hints:["print() を3回書きます","1つのprint()で1行表示されます","print(\"Python\")\\nprint(\"は\")\\nprint(\"楽しい！\")"]}},
{id:"s3",title:"計算もできる！",xp:40,
content:[{type:"text",body:"## Pythonは超高性能な電卓！🧮\n\nprint()の中に計算式を書くと、答えを表示してくれる：\n\n<span class=\"copyable\">print(10 + 3)</span> → 13\n<span class=\"copyable\">print(100 - 25)</span> → 75"},{type:"code",code:"print(6 * 7)     # 掛け算は * を使う\nprint(10 / 3)    # 割り算は / を使う",desc:"掛け算は×じゃなくて*（Shift+8）、割り算は÷じゃなくて/"},{type:"text",body:"### 計算記号まとめ\n\n| やりたいこと | 数学 | Python |\n|---|---|---|\n| 足し算 | + | `+` |\n| 引き算 | − | `-` |\n| 掛け算 | × | `*`（Shift+8）|\n| 割り算 | ÷ | `/` |"},{type:"tip",body:"💡 電卓より便利なのは、**計算式を保存して何度でも使い回せる**こと。次のレッスンで学ぶ「変数」と組み合わせると最強になるよ！"}],exercise:{instruction:"1980円の商品に消費税10%を足した合計金額を計算して表示してください。\nヒント: 1980 + 1980 * 0.1 または 1980 * 1.1",initialCode:"# 税込価格を計算して表示！\n",expectedOutput:"2178.0",keywords:["print","1980"],answer:"print(1980 * 1.1)",hints:["print() の中に計算式を書きます","1980 * 1.1 で税込価格が出ます","print(1980 * 1.1) と書いてみてください"]}}
]},

// ========== 2. Python基礎マスター ==========
{id:"py-basics",title:"Python基礎マスター",desc:"変数・データ型・文字列・計算。Pythonの土台をしっかり固めよう",level:"b",icon:"🐣",free:true,nextCourse:"py-control",lessons:[
{id:"b1",title:"変数 - データに名前をつける箱",xp:50,
content:[{type:"text",body:"## <span class=\"term\" data-term=\"variable\">変数</span>ってなに？📦\n\n変数は**名前つきの箱**だと思って！\n\n引っ越しのとき、段ボールに「食器」「本」ってラベル貼るよね？ プログラミングの変数もまったく同じ。**データに名前をつけて保存**して、あとから名前で取り出す。"},{type:"code",code:"name = \"太郎\"    # nameという箱に「太郎」を入れる\nage = 20         # ageという箱に 20 を入れる\n\nprint(name)      # → 太郎\nprint(age)       # → 20",desc:"= は「等しい」じゃなくて「入れる」という意味！"},{type:"text",body:"### 箱の中身は変えられる\n\n<span class=\"copyable\">age = 20</span> → 20が入ってる\n<span class=\"copyable\">age = 21</span> → 21に上書きされた！\n\n### 名前のルール\n- ✅ 英字、数字、`_` が使える\n- ❌ 数字で始めるのはダメ（`1name` → エラー）\n- ⚠️ 大文字小文字は区別される（`Name` と `name` は別の箱）"},{type:"tip",body:"💡 `x = 25` より <span class=\"copyable\">age = 25</span> の方が「あ、年齢だな」ってわかるよね。**中身がわかる名前をつける**のがプロのコツ！"}],exercise:{instruction:"変数 fruit に \"りんご\" を代入し、変数 price に 150 を代入して、それぞれ表示してください。",initialCode:"# 変数を定義して表示しよう\n",expectedOutput:"りんご\n150",keywords:["fruit","price","print"],answer:"fruit = \"りんご\"\nprice = 150\nprint(fruit)\nprint(price)",hints:["fruit = \"りんご\" で変数に文字列を代入","price = 150 で数字を代入（クォートなし）","print(fruit) と print(price) で表示"]}},
{id:"b2",title:"データの種類 - データ型",xp:50,
content:[{type:"text",body:"## <span class=\"term\" data-term=\"data-type\">データ型</span>って何？🏷️\n\n日常でも「3」と「りんご」は違うものだよね。「3 + 5」は計算できるけど、「りんご + みかん」は計算できない。\n\nPythonも同じで、データには**種類（型）**がある：\n\n| 型 | 何？ | 書き方 |\n|---|---|---|\n| <span class=\"term\" data-term=\"int\">int</span> | 整数 | `42`, `-10` |\n| <span class=\"term\" data-term=\"float\">float</span> | 小数 | `3.14`, `-0.5` |\n| <span class=\"term\" data-term=\"str\">str</span> | 文字列 | `\"Hello\"` |\n| <span class=\"term\" data-term=\"bool\">bool</span> | はい/いいえ | `True`, `False` |"},{type:"code",code:"x = 42            # int（整数）\ny = 3.14          # float（小数）\nname = \"Python\"   # str（文字列）\n\n# type()で「この箱の中身は何型？」と聞ける\nprint(type(x))    # → <class 'int'>",desc:"type()はデータの種類を教えてくれる便利な命令"},{type:"tip",body:"💡 型を意識するのは**計算のとき**。`\"3\" + \"5\"` は `\"35\"`（文字の結合）、`3 + 5` は `8`（数字の足し算）。見た目は似てるけど全然違う！"}],exercise:{instruction:"変数 a に 42 を、変数 b に 3.14 を、変数 c に \"Hello\" を代入し、それぞれのtype()を表示してください。",initialCode:"# 3つの変数を定義してtype()で確認\n",expectedOutput:"<class 'int'>\n<class 'float'>\n<class 'str'>",keywords:["type","print"],answer:"a = 42\nb = 3.14\nc = \"Hello\"\nprint(type(a))\nprint(type(b))\nprint(type(c))",hints:["a = 42 で整数を代入","type(a) で型を取得","print(type(a)) で型を表示"]}},
{id:"b3",title:"文字列を自在に操ろう",xp:60,
content:[{type:"text",body:"## 文字列を自在に操ろう！✂️\n\n文字列は `+` でつなげられる。でももっと便利なのが **<span class=\"term\" data-term=\"f-string\">f文字列</span>**（エフもじれつ）！\n\n文字列の前に `f` をつけて、`{}` の中に変数を入れるだけ："},{type:"code",code:"name = \"太郎\"\nage = 20\n\n# f文字列 → 超便利！\nprint(f\"{name}さんは{age}歳です\")\n# → 太郎さんは20歳です",desc:"fをつけて{}に変数を入れるだけ！"},{type:"text",body:"### 文字列でよく使うワザ\n\n<span class=\"copyable\">msg.upper()</span> → 全部大文字に\n<span class=\"copyable\">msg.title()</span> → 先頭だけ大文字に\n<span class=\"copyable\">len(msg)</span> → 文字数を数える"},{type:"tip",body:"💡 <span class=\"term\" data-term=\"f-string\">f文字列</span>の `f` を忘れると `{name}さん` がそのまま表示されちゃう。`f` は「フォーマット」のf。絶対忘れないで！"}],exercise:{instruction:"変数 item に \"コーヒー\"、変数 price に 350 を代入し、f文字列で「コーヒーは350円です」と表示してください。",initialCode:"# f文字列で表示しよう\n",expectedOutput:"コーヒーは350円です",keywords:["print","f\""],answer:"item = \"コーヒー\"\nprice = 350\nprint(f\"{item}は{price}円です\")",hints:["item = \"コーヒー\" で文字列代入","f\"...\" でf文字列を作る","print(f\"{item}は{price}円です\")"]}},
{id:"b4",title:"Pythonで計算しよう - 演算子",xp:60,
content:[{type:"text",body:"## 計算をもっと深く！🔢\n\n基本の四則演算に加えて、Python には便利な演算子がある：\n\n| 演算子 | 意味 | 例 |\n|---|---|---|\n| `+` `-` `*` `/` | 四則演算 | `10 + 3` → 13 |\n| `//` | 割り算の**整数部分だけ** | `10 // 3` → 3 |\n| `%` | 割り算の**余り** | `10 % 3` → 1 |\n| `**` | **べき乗**（◯の◯乗） | `2 ** 3` → 8 |"},{type:"code",code:"total = 4200\npeople = 3\n\nprint(total // people)   # → 1400（1人あたり）\nprint(total % people)    # → 0（余り）",desc:"//で割り勘、%で余りを計算！"},{type:"text",body:"### 実用例：割り勘計算\n\n4200円を3人で割ると？\n- `4200 // 3` → **1人1400円**\n- `4200 % 3` → **余り0円**\n\nf文字列と組み合わせると読みやすい：\n<span class=\"copyable\">print(f\"1人{total // people}円（余り{total % people}円）\")</span>"},{type:"tip",body:"💡 `//`と`%`はセットで覚えよう。「何個入る？」が`//`、「いくつ余る？」が`%`。飲み会の割り勘、お菓子の分配、時間計算（秒→分:秒）で大活躍！"}],exercise:{instruction:"3人で4200円の食事を割り勘します。1人分（//で切り捨て）と余りを計算し「1人1400円（余り0円）」と表示してください。",initialCode:"# 割り勘を計算\n",expectedOutput:"1人1400円（余り0円）",keywords:["//","%","print"],answer:"total = 4200\npeople = 3\nprint(f\"1人{total // people}円（余り{total % people}円）\")",hints:["total // people で1人分","total % people で余り","f文字列で1つのprintにまとめる"]}},
{id:"b5",title:"型変換 - データの変身",xp:60,
content:[{type:"text",body:"## 型変換 - データの変身！🔄\n\n`\"100\"` と `100` は見た目は同じでも、Pythonにとっては全く別物。\n\n- `\"100\"` → **文字列**（str）: テキストとして扱う\n- `100` → **整数**（int）: 計算に使える\n\n文字列の数字を計算に使いたいときは、**型変換**が必要！"},{type:"code",code:"# ❌ これはエラー！\n# print(\"100\" + 50)  # str + int はダメ\n\n# ✅ int()で文字列→整数に変換！\nprint(int(\"100\") + 50)  # → 150",desc:"int()で文字列を整数に、str()で整数を文字列に変換"},{type:"text",body:"### 変換まとめ\n\n| 変換 | 関数 | 例 |\n|---|---|---|\n| 文字→整数 | `int()` | `int(\"42\")` → 42 |\n| 文字→小数 | `float()` | `float(\"3.14\")` → 3.14 |\n| 数字→文字 | `str()` | `str(100)` → \"100\" |"},{type:"tip",body:"💡 ユーザー入力（input()で受け取る値）は**必ず文字列**。計算するなら `int()` か `float()` で変換するのを忘れずに！"}],exercise:{instruction:"変数 a に文字列 \"80\"、変数 b に文字列 \"20\" を代入し、int()で整数に変換してから足し算した結果を表示してください。",initialCode:"# 文字列を数字に変換して計算\n",expectedOutput:"100",keywords:["int","print"],answer:"a = \"80\"\nb = \"20\"\nprint(int(a) + int(b))",hints:["a = \"80\" で文字列として定義","int(a) で整数に変換","print(int(a) + int(b))"]}}
]},

// ========== 3. 条件分岐とループ ==========
{id:"py-control",title:"条件分岐とループ",desc:"if文・for文・while文で、プログラムに判断と繰り返しをさせよう",level:"b",icon:"🔀",free:true,nextCourse:"py-func",lessons:[
{id:"c1",title:"もし〜なら - if文の基本",xp:60,
content:[{type:"text",body:"## もし〜なら → if文！🚦\n\n信号を想像してみて：\n- 🟢 **青なら** → 渡る\n- 🔴 **赤なら** → 止まる\n\nプログラムも同じように「条件によって動きを変える」ことができる。それが **if文**！"},{type:"code",code:"score = 85\n\nif score >= 80:\n    print(\"合格！\")",desc:"scoreが80以上ならprintが実行される"},{type:"text",body:"### if文の書き方ルール\n\n1. `if` のあとに**条件**を書く\n2. 行の最後に **`:`（コロン）** を忘れずに\n3. 次の行は **半角スペース4つ**で字下げ（インデント）\n\n⚠️ **インデントは超重要！** Pythonはインデントで「どこまでがif文の中身か」を判断する。ズレるとエラーになるよ。\n\n### 比較演算子\n| 書き方 | 意味 |\n|---|---|\n| `==` | 等しい |\n| `!=` | 等しくない |\n| `>` `<` | より大きい/小さい |\n| `>=` `<=` | 以上/以下 |"},{type:"tip",body:"💡 `=` は「代入（入れる）」、`==` は「等しいか？」。1つと2つで全然違うから注意！ `if score = 80:` はエラー。正しくは `if score == 80:`"}],exercise:{instruction:"変数 score に 85 を代入し、80以上なら「合格！」と表示してください。",initialCode:"# スコアで合格判定\n",expectedOutput:"合格！",keywords:["if","print","score"],answer:"score = 85\nif score >= 80:\n    print(\"合格！\")",hints:["score = 85 で定義","if score >= 80: で条件判定","print(\"合格！\") をインデントして書く"]}},
{id:"c2",title:"もっと条件を - elif と else",xp:60,
content:[{type:"text",body:"## もっと条件を！elif と else 🔀\n\nif文だけだと「条件に合うとき」しか処理できない。**合わないときも何かしたい**よね？\n\n- `else` → ifの条件に合わないとき\n- `elif` → 「それとも、こっちの条件なら？」（else + if の略）"},{type:"code",code:"age = 17\n\nif age >= 18:\n    print(\"成人です\")\nelse:\n    print(\"未成年です\")\n# → 未成年です",desc:"ifに合わないときはelseの中身が実行される"},{type:"text",body:"### elifで3つ以上に分岐\n\n<span class=\"copyable\">score = 75</span>\n\n```\nif score >= 90:     → 「A」\nelif score >= 70:   → 「B」（90未満でかつ70以上）\nelif score >= 50:   → 「C」\nelse:               → 「D」（どれにも当てはまらない）\n```\n\n上から順にチェックして、**最初に合った条件**だけ実行される。だからelifの順番は大事！"},{type:"tip",body:"💡 `elif` はいくつでも書ける。`else` は最後に1つだけ。「条件に合うものが1つもなかったとき」の処理を書く場所だよ。"}],exercise:{instruction:"変数 age に 17 を代入し、18以上なら「成人です」、そうでなければ「未成年です」と表示してください。",initialCode:"# 年齢判定\n",expectedOutput:"未成年です",keywords:["if","else","print"],answer:"age = 17\nif age >= 18:\n    print(\"成人です\")\nelse:\n    print(\"未成年です\")",hints:["age = 17 で定義","if age >= 18: で18歳以上チェック","else: で「それ以外」を処理"]}},
{id:"c3",title:"繰り返し① - for文",xp:60,
content:[{type:"text",body:"## 繰り返し① - for文 🔁\n\n同じことを5回書くのはダルいよね？\n\n```\nprint(1)\nprint(2)\nprint(3)\nprint(4)\nprint(5)\n```\n\n→ **for文**を使えば1行でOK！"},{type:"code",code:"for i in range(1, 6):\n    print(i)\n# → 1, 2, 3, 4, 5 と表示される",desc:"range(1, 6)は1から5まで。6は含まれないよ！"},{type:"text",body:"### range()の使い方\n\n- `range(5)` → 0, 1, 2, 3, 4（**0から始まる**、5は含まない）\n- `range(1, 6)` → 1, 2, 3, 4, 5（1から5まで）\n- `range(0, 10, 2)` → 0, 2, 4, 6, 8（2ずつ増える）\n\n### リストをループ\n\n数字だけじゃなく、リストの中身を1つずつ取り出せる：\n\n<span class=\"copyable\">for fruit in [\"りんご\", \"バナナ\", \"みかん\"]:</span>\n<span class=\"copyable\">    print(fruit)</span>"},{type:"tip",body:"💡 `range(1, 6)` で「6は含まれない」のが最初ピンと来ないかも。**range(開始, 終了)のとき、終了は含まれない**。これはPythonのお約束！"}],exercise:{instruction:"for文を使って、1から5までの数字を1行ずつ表示してください。",initialCode:"# 1から5まで表示\n",expectedOutput:"1\n2\n3\n4\n5",keywords:["for","range","print"],answer:"for i in range(1, 6):\n    print(i)",hints:["range(1, 6) で1~5の範囲","for i in range(1, 6): でループ","print(i) で数字を表示"]}},
{id:"c4",title:"繰り返し② - while文",xp:70,
content:[{type:"text",body:"## 繰り返し② - while文 ⏳\n\nfor文は「回数が決まってる」ときに便利。**while文**は「条件が満たされてる間ずっと繰り返す」ときに使う。\n\nイメージ：\n- for文 → 「5回やって！」\n- while文 → 「お腹いっぱいになるまで食べて！」"},{type:"code",code:"n = 1\nwhile n <= 5:    # nが5以下の間、繰り返す\n    print(n)\n    n += 1       # nを1増やす（これ忘れると無限ループ！）\nprint(\"完了\")",desc:"n += 1 を忘れるとnがずっと1のまま → 永遠に終わらない！"},{type:"text",body:"### ⚠️ 無限ループに注意！\n\n`while` は条件が `True` の間ずっと回り続ける。**条件が変わる処理**（`n += 1` など）を忘れると、プログラムが永遠に止まらなくなる！\n\n### for vs while の使い分け\n| 場面 | 使う文 |\n|---|---|\n| 回数がわかってる | `for` |\n| 条件で止めたい | `while` |\n| リストを回す | `for` |\n| ユーザー入力待ち | `while` |"},{type:"tip",body:"💡 while文が怖かったら、まずはfor文だけ使ってOK！ 実は90%以上の場面はforで書ける。whileが本当に必要になるのは「何回繰り返すかわからない」ときだけ。"}],exercise:{instruction:"while文で n=1 から始めて、n<=5 の間 n を表示し、最後に「完了」と表示してください。",initialCode:"# while文で1~5表示\n",expectedOutput:"1\n2\n3\n4\n5\n完了",keywords:["while","print"],answer:"n = 1\nwhile n <= 5:\n    print(n)\n    n += 1\nprint(\"完了\")",hints:["n = 1 で初期化","while n <= 5: で条件","print(n) の後に n += 1 を忘れずに"]}},
{id:"c5",title:"条件の組み合わせ - and, or, not",xp:70,
content:[{type:"text",body:"## 条件の組み合わせ 🧩\n\n「点数が60以上 **かつ** 出席率OK」みたいに、条件を組み合わせたいときがあるよね。\n\n| 演算子 | 意味 | 例 |\n|---|---|---|\n| `and` | **両方**満たす | `A and B` → AもBもTrue |\n| `or` | **どちらか**満たす | `A or B` → AかBがTrue |\n| `not` | **反転** | `not A` → AがTrueならFalse |"},{type:"code",code:"score = 75\nattendance = True\n\nif score >= 60 and attendance:\n    print(\"合格\")\nelse:\n    print(\"不合格\")\n# → 合格（75点 >= 60 かつ 出席OK）",desc:"andは「両方」、orは「どっちか」"},{type:"text",body:"### 実用例\n\n- **ログイン判定**: `if username == \"admin\" and password == \"1234\":`\n- **年齢チェック**: `if age < 13 or age > 65:` （子供またはシニア）\n- **否定**: `if not is_banned:` （BANされていなければ）\n\n複雑な条件はカッコ `()` でグループ化すると読みやすい：\n\n<span class=\"copyable\">if (score >= 60) and (attendance == True):</span>"},{type:"tip",body:"💡 `attendance == True` は `attendance` だけでOK。Pythonでは変数がTrueかどうかを直接ifに書ける。逆にFalseかチェックするなら `if not attendance:`"}],exercise:{instruction:"score=75, attendance=True。「score>=60 かつ attendance==True」なら「合格」、そうでなければ「不合格」と表示。",initialCode:"# 合格判定\n",expectedOutput:"合格",keywords:["and","if","print"],answer:"score = 75\nattendance = True\nif score >= 60 and attendance:\n    print(\"合格\")\nelse:\n    print(\"不合格\")",hints:["score = 75, attendance = True","if score >= 60 and attendance:","条件を満たすので「合格」"]}}
]},

// ========== 4. 関数をマスター ==========
{id:"py-func",title:"関数をマスター",desc:"コードを整理して再利用。def・引数・戻り値を学ぼう",level:"b",icon:"⚡",free:true,nextCourse:"py-ds",lessons:[
{id:"f1",title:"関数って何？ - 料理レシピのように",xp:70,
content:[{type:"text",body:"## 関数ってなに？🍳\n\n料理で考えてみよう。「カレーの作り方」をレシピに書いておけば、何度でも同じカレーが作れるよね？\n\n関数はプログラミングの**レシピ**。一度書いたら何度でも呼び出せる！"},{type:"code",code:"# レシピ（関数）を書く\ndef add(a, b):\n    return a + b\n\n# レシピを使う（呼び出す）\nprint(add(3, 7))    # → 10\nprint(add(100, 50)) # → 150",desc:"defで「定義」、return で「結果を返す」"},{type:"text",body:"### 関数の3ステップ\n\n1. **`def 関数名(引数):`** → レシピの名前と材料を決める\n2. **処理を書く** → インデント（字下げ）して中身を書く\n3. **`return 結果`** → 出来上がりを返す\n\n`add(3, 7)` と呼ぶと、`a=3, b=7` が入って、`return 10` が返ってくるイメージ。"},{type:"tip",body:"💡 関数は**使う前に定義**しないとダメ。Pythonは上から順に読むから、`def add(...)` より前に `add(3, 7)` を書くとエラーになるよ！"}],exercise:{instruction:"引数 a と b の合計を返す関数 add を作り、add(3, 7) の結果を表示してください。",initialCode:"# add関数を定義\n",expectedOutput:"10",keywords:["def","return","print"],answer:"def add(a, b):\n    return a + b\nprint(add(3, 7))",hints:["def add(a, b): で定義","return a + b で合計を返す","print(add(3, 7)) で表示"]}},
{id:"f2",title:"引数と戻り値",xp:70,
content:[{type:"text",body:"## 引数と戻り値 📥📤\n\n関数を自販機だと思ってみて：\n\n- **引数（ひきすう）** = 投入するお金 → 関数に渡すデータ\n- **戻り値（もどりち）** = 出てくるジュース → 関数が返す結果\n\n<span class=\"copyable\">ジュース = 自販機(お金)</span>\n<span class=\"copyable\">result = function(input)</span>"},{type:"code",code:"def discount(price):\n    return int(price * 0.9)   # 10%引き\n\nresult = discount(1000)\nprint(result)  # → 900",desc:"priceという引数を受け取り、割引後の値段を返す"},{type:"text",body:"### 引数は複数OK\n\n<span class=\"copyable\">def greet(name, time):</span>\n<span class=\"copyable\">    return f\"{time}、{name}さん！\"</span>\n\n→ `greet(\"太郎\", \"おはよう\")` で `\"おはよう、太郎さん！\"`\n\n### returnがないとどうなる？\n\nreturnを書かないと `None`（何もない）が返る。printで表示するだけなら問題ないけど、**結果を使いたいならreturn必須**。"},{type:"tip",body:"💡 return と print の違い：`return` は結果を**返す**（あとで使える）。`print` は画面に**表示するだけ**（使い回せない）。迷ったら `return` を使おう！"}],exercise:{instruction:"価格を受け取り、10%割引後の価格を返す関数 discount を作り、discount(1000) の結果を表示してください。",initialCode:"# 割引関数\n",expectedOutput:"900",keywords:["def","return","print"],answer:"def discount(price):\n    return int(price * 0.9)\nprint(discount(1000))",hints:["def discount(price): で定義","price * 0.9 で10%割引","return int(...) で整数にして返す"]}},
{id:"f3",title:"デフォルト引数",xp:70,
content:[{type:"text",body:"## デフォルト引数 🎁\n\nカフェの注文を想像して：\n- 「コーヒーください」→ ホットが出てくる（デフォルト）\n- 「アイスコーヒーください」→ アイスが出てくる（指定）\n\n関数の引数にも**デフォルト値（初期値）**を設定できる！"},{type:"code",code:"def greet(name, greeting=\"こんにちは\"):\n    print(f\"{greeting}、{name}さん！\")\n\ngreet(\"太郎\")              # → こんにちは、太郎さん！\ngreet(\"花子\", \"おはよう\")  # → おはよう、花子さん！",desc:"greetingを省略するとデフォルトの「こんにちは」が使われる"},{type:"text",body:"### ルール\n\n- デフォルト引数は**後ろ**に書く（`def f(必須, 任意=\"初期値\")`）\n- 呼び出し時に省略するとデフォルト値が使われる\n- 指定すれば上書きされる\n\n実用例：税率計算\n\n<span class=\"copyable\">def calc_tax(price, rate=0.1):</span>\n<span class=\"copyable\">    return int(price * (1 + rate))</span>\n\n→ `calc_tax(1000)` で10%、`calc_tax(1000, 0.08)` で8%"},{type:"tip",body:"💡 デフォルト引数は「ほとんどの場合こうだけど、たまに変えたい」ときに使う。毎回違う値を渡すなら通常の引数でOK。"}],exercise:{instruction:"greet(name, greeting=\"こんにちは\") を定義し、greet(\"太郎\") と greet(\"花子\", \"おはよう\") を呼び出してください。",initialCode:"# デフォルト引数付き関数\n",expectedOutput:"こんにちは、太郎さん！\nおはよう、花子さん！",keywords:["def","print"],answer:"def greet(name, greeting=\"こんにちは\"):\n    print(f\"{greeting}、{name}さん！\")\ngreet(\"太郎\")\ngreet(\"花子\", \"おはよう\")",hints:["def greet(name, greeting=\"こんにちは\"):","print(f\"{greeting}、{name}さん！\")","greet を2回呼び出す"]}},
{id:"f4",title:"ラムダ式 - 1行で関数を",xp:80,
content:[{type:"text",body:"## ラムダ式 - 1行で関数を書く ⚡\n\n`def` で関数を定義するのは2行以上かかる。**ちょっとした計算だけ**の関数を、1行で書けるのが `lambda`（ラムダ）！"},{type:"code",code:"# 普通の関数\ndef triple(x):\n    return x * 3\n\n# ラムダ式（同じことを1行で！）\ntriple = lambda x: x * 3\n\nprint(triple(7))  # → 21",desc:"lambda 引数: 戻り値  ← これだけ！"},{type:"text",body:"### いつ使う？\n\n正直、**初心者はdefだけで十分**。lambdaが便利なのは：\n\n- リストの並び替え: `sorted(users, key=lambda u: u[\"age\"])`\n- 簡単なフィルター: `filter(lambda x: x > 0, numbers)`\n\n今は「defを1行で書ける書き方がある」くらいの認識でOK！"},{type:"tip",body:"💡 lambda は `return` を書かない。`lambda x: x * 3` は自動的に `x * 3` を返す。逆に言うと、複数の処理や条件分岐が必要なら `def` を使おう。"}],exercise:{instruction:"ラムダ式で引数を3倍する関数 triple を定義し、triple(7) の結果を表示してください。",initialCode:"# ラムダ式\n",expectedOutput:"21",keywords:["lambda","print"],answer:"triple = lambda x: x * 3\nprint(triple(7))",hints:["lambda x: x * 3","triple = lambda x: x * 3","print(triple(7))"]}}
]},

// ========== 5. データ構造 ==========
{id:"py-ds",title:"データ構造",desc:"リスト・辞書・タプル・リスト内包表記でデータを効率管理",level:"i",icon:"📦",free:true,nextCourse:"py-clean",lessons:[
{id:"d1",title:"リスト - データの列",xp:80,
content:[{type:"text",body:"## <span class=\"term\" data-term=\"list\">リスト</span> - データの列 📋\n\n変数は1つのデータしか入らない箱。**リスト**は「データを順番に並べて入れられる棚」！\n\n<span class=\"copyable\">fruits = [\"りんご\", \"バナナ\", \"みかん\"]</span>\n\n`[]`（角カッコ）で囲んで、カンマで区切る。"},{type:"code",code:"numbers = [3, 1, 4, 1, 5]\n\n# 中身を取り出す（0番目から！）\nprint(numbers[0])    # → 3（最初）\nprint(numbers[-1])   # → 5（最後）\n\n# 並び替え\nnumbers.sort()\nprint(numbers)       # → [1, 1, 3, 4, 5]",desc:"[0]で最初、[-1]で最後。sortで昇順に"},{type:"text",body:"### よく使うリスト操作\n\n| やること | 書き方 | 例 |\n|---|---|---|\n| 追加 | `.append(値)` | `fruits.append(\"桃\")` |\n| 削除 | `.remove(値)` | `fruits.remove(\"バナナ\")` |\n| 長さ | `len(リスト)` | `len(fruits)` → 3 |\n| 並び替え | `.sort()` | `numbers.sort()` |"},{type:"tip",body:"💡 リストの番号は**0から始まる**。人間は「1番目」から数えるけど、プログラミングは「0番目」から。これは全プログラミング言語共通のルール！"}],exercise:{instruction:"[3, 1, 4, 1, 5] をsort()でソートして表示してください。",initialCode:"# ソートして表示\n",expectedOutput:"[1, 1, 3, 4, 5]",keywords:["sort","print"],answer:"numbers = [3, 1, 4, 1, 5]\nnumbers.sort()\nprint(numbers)",hints:["numbers = [3, 1, 4, 1, 5]","numbers.sort() でソート","print(numbers)"]}},
{id:"d2",title:"辞書 - 名前でデータを引く",xp:80,
content:[{type:"text",body:"## <span class=\"term\" data-term=\"dict\">辞書</span> - 名前でデータを引く 📖\n\n英和辞書って「apple → りんご」みたいに**キーと値**のペアだよね？\n\nPythonの辞書もまったく同じ。**名前（キー）で値を取り出せる**データ構造！"},{type:"code",code:"item = {\n    \"name\": \"ノートPC\",\n    \"price\": 98000\n}\n\n# キーで値を取り出す\nprint(item[\"name\"])    # → ノートPC\nprint(item[\"price\"])   # → 98000\n\n# f文字列と組み合わせ\nprint(f\"{item['name']}: {item['price']}円\")",desc:"{キー: 値} で定義。[キー] で取り出す"},{type:"text",body:"### リスト vs 辞書\n\n| | リスト | 辞書 |\n|---|---|---|\n| 書き方 | `[値, 値]` | `{キー: 値}` |\n| 取り出し | **番号**で | **名前**で |\n| 用途 | 順番が大事なデータ | 名前つきデータ |\n| 例 | 成績の点数一覧 | ユーザー情報 |"},{type:"tip",body:"💡 辞書は「このデータの名前は？ 値は？」がハッキリしてるときに使う。APIのレスポンス、設定ファイル、ユーザーデータ…実務で一番使うデータ構造かも！"}],exercise:{instruction:"商品辞書を作成。\"name\":\"ノートPC\", \"price\":98000。f文字列で「ノートPC: 98000円」と表示。",initialCode:"# 商品辞書\n",expectedOutput:"ノートPC: 98000円",keywords:["print"],answer:"item = {\"name\": \"ノートPC\", \"price\": 98000}\nprint(f\"{item['name']}: {item['price']}円\")",hints:["item = {\"name\": \"ノートPC\", \"price\": 98000}","item[\"name\"] でアクセス","f文字列でまとめて表示"]}},
{id:"d3",title:"タプルとセット",xp:80,
content:[{type:"text",body:"## タプルとセット 🔒🎯\n\n### タプル — 変更できないリスト\n\nリストは中身を変えられるけど、**タプル**は一度作ったら変更不可。\n\n<span class=\"copyable\">point = (10, 20)</span> → カッコ `()` で作る\n\n「この値は変えちゃダメ！」ってデータに使う（座標、RGB色など）。\n\n### セット — 重複なしの集合\n\n<span class=\"copyable\">colors = {\"赤\", \"青\", \"赤\", \"緑\"}</span> → `{\"赤\", \"青\", \"緑\"}` （重複が消える！）"},{type:"code",code:"# セットで重複を消す\ndata = [1, 2, 2, 3, 3, 3, 4]\nunique = set(data)        # → {1, 2, 3, 4}\nprint(len(unique))        # → 4（ユニークな値の数）",desc:"set()に通すだけで重複が消える！"},{type:"text",body:"### まとめ\n\n| 種類 | 書き方 | 変更 | 重複 | 用途 |\n|---|---|---|---|---|\n| リスト | `[]` | ⭕ | あり | 一般的なデータ |\n| タプル | `()` | ❌ | あり | 変えたくないデータ |\n| セット | `{}` | ⭕ | なし | ユニーク値 |"},{type:"tip",body:"💡 実務で一番使うのはリストと辞書。タプルとセットは「知ってると便利な場面がある」レベル。今は存在を知っておくだけで十分！"}],exercise:{instruction:"リスト [1, 2, 2, 3, 3, 3, 4] からset()で重複を除き、要素数をlen()で表示してください。",initialCode:"# 重複を除く\n",expectedOutput:"4",keywords:["set","len","print"],answer:"data = [1, 2, 2, 3, 3, 3, 4]\nprint(len(set(data)))",hints:["set() でセットに変換","len() で要素数","print(len(set(data)))"]}},
{id:"d4",title:"リスト内包表記",xp:90,
content:[{type:"text",body:"## リスト内包表記 🚀\n\nfor文でリストを作るのを**1行**にギュッと圧縮できる書き方。最初は魔法に見えるけど、慣れるとめちゃ便利！"},{type:"code",code:"# 普通のfor文（3行）\nresult = []\nfor i in range(1, 6):\n    result.append(i ** 2)\n\n# リスト内包表記（1行！）\nresult = [i ** 2 for i in range(1, 6)]\nprint(result)  # → [1, 4, 9, 16, 25]",desc:"[式 for 変数 in 範囲] — やってることは同じ！"},{type:"text",body:"### 条件つきもOK\n\n1〜10の奇数だけ取り出す：\n\n<span class=\"copyable\">odds = [i for i in range(1, 11) if i % 2 != 0]</span>\n→ `[1, 3, 5, 7, 9]`\n\n読み方：「**i を range(1,11) から取り出して、i%2!=0 のやつだけ集める**」"},{type:"tip",body:"💡 リスト内包表記は強力だけど、長くなりすぎると読みにくい。**1行で読めないくらい複雑なら普通のfor文で書く**のがプロの判断。可読性 > 短さ！"}],exercise:{instruction:"リスト内包表記で1~10の奇数リストを作り表示してください。",initialCode:"# 奇数リスト\n",expectedOutput:"[1, 3, 5, 7, 9]",keywords:["for","if"],answer:"odds = [i for i in range(1, 11) if i % 2 != 0]\nprint(odds)",hints:["range(1, 11) で1~10","i % 2 != 0 で奇数判定","[i for i in range(1, 11) if i % 2 != 0]"]}}
]},

// ========== 6. きれいなコードの書き方 ==========
{id:"py-clean",title:"きれいなコードの書き方",desc:"コメント・命名規則・コードの整理。読みやすいコードを書こう",level:"i",icon:"✨",free:true,nextCourse:"py-error",lessons:[
{id:"cl1",title:"コメント - 未来の自分へのメモ",xp:70,
content:[{type:"text",body:"## <span class=\"term\" data-term=\"comment\">コメント</span>って何？📝\n\nコメントは「未来の自分へのメモ」。`#` の後ろに書いた文字はPythonに**完全に無視**される。\n\n1ヶ月後の自分は、今の自分とは別人。「このコード何やってたっけ？」ってならないために書くんだよ。"},{type:"code",code:"# 消費税率（2024年時点）\nTAX_RATE = 0.1\n\ndef calc_total(price):\n    \"\"\"税込価格を計算する関数\"\"\"\n    return int(price * (1 + TAX_RATE))\n\nprint(calc_total(1000))  # → 1100",desc:"# で1行コメント。\"\"\"\"\"\"で関数の説明（docstring）"},{type:"text",body:"### いいコメント vs 悪いコメント\n\n❌ **悪い例**: `x = x + 1  # xに1を足す`\n→ コード読めばわかる。無駄。\n\n✅ **良い例**: `x = x + 1  # リトライ回数をカウント`\n→ **なぜ**そうするのかがわかる！\n\nコメントは「何をしてるか」じゃなく「**なぜそうしてるか**」を書くのがコツ。"},{type:"tip",body:"💡 `\"\"\"三重クォート\"\"\"` は**docstring（ドキュメント文字列）**。関数の直後に書くと、`help(関数名)` で説明を確認できるようになる。チーム開発では必須！"}],exercise:{instruction:"以下のコードにコメントを追加して実行してください。\n1行目の上に # で「1~5の2乗リストを作成」というコメントを書いてください。",initialCode:"# ここにコメントを書いてね\nresult = [i ** 2 for i in range(1, 6)]\nprint(result)",expectedOutput:"[1, 4, 9, 16, 25]",keywords:["#","print"],answer:"# 1~5の2乗リストを作成\nresult = [i ** 2 for i in range(1, 6)]\nprint(result)",hints:["# でコメントを書く","コードの上に説明を書く","# 1~5の2乗リストを作成"]}},
{id:"cl2",title:"変数名のつけ方",xp:70,
content:[{type:"text",body:"## 変数名のつけ方 🏷️\n\nこの2つ、どっちが読みやすい？\n\n❌ `x = 1000; y = 0.1; print(int(x + x * y))`\n✅ `price = 1000; tax_rate = 0.1; print(int(price + price * tax_rate))`\n\n名前をつけるだけで、コメントなしでも読める！\n\n### Pythonの命名ルール（PEP8）\n\n| 種類 | 書き方 | 例 |\n|---|---|---|\n| 変数・関数 | snake_case | `user_name`, `calc_tax()` |\n| 定数 | UPPER_CASE | `TAX_RATE`, `MAX_COUNT` |\n| クラス | PascalCase | `BankAccount` |"},{type:"code",code:"# ❌ 何の変数かわからない\nx = 1000\ny = 0.1\nprint(int(x + x * y))\n\n# ✅ 名前だけで意味がわかる\nprice = 1000\ntax_rate = 0.1\nprint(int(price + price * tax_rate))",desc:"変数名は「中身がわかる名前」にしよう"},{type:"text",body:"### NGな名前\n\n- `data`, `info` → 何のデータ？具体的に！\n- `a`, `b`, `x` → ループカウンタ以外で1文字はNG\n- `myList` → 型名を入れるのは冗長\n\n**声に出してみるテスト**: `user_age = 25` → 「ユーザーの年齢は25」。自然に読めるならOK！"},{type:"tip",body:"💡 英語に自信がなくても大丈夫。Google翻訳で「消費税率」→ `tax_rate` と調べればOK。ローマ字（`syouhizei`）は避けよう。"}],exercise:{instruction:"変数名をわかりやすく書き換えて同じ結果を出してください。\nx = 1000\ny = 0.1\nprint(int(x + x * y))",initialCode:"# 変数名をわかりやすく！\n",expectedOutput:"1100",keywords:["print"],answer:"price = 1000\ntax_rate = 0.1\nprint(int(price + price * tax_rate))",hints:["x は何？→ price","y は何？→ tax_rate","名前を変えるだけ"]}},
{id:"cl3",title:"関数で整理整頓 - DRY原則",xp:80,
content:[{type:"text",body:"## DRY原則 🔄\n\n**DRY = Don't Repeat Yourself**（繰り返すな）\n\n同じコードが2回以上出てきたら、それは**関数にまとめるサイン**！\n\nなぜ繰り返しがダメなのか？\n- 🔧 **修正が3倍大変**: 3箇所に同じコード → 修正も3箇所\n- 🐛 **バグの温床**: 1箇所だけ修正忘れ → 不具合\n- 📖 **読みにくい**: 同じコードが何度も出ると本質が見えない"},{type:"code",code:"# ❌ DRY違反（同じパターン3回）\nprint(f\"太郎: {85}点\")\nprint(f\"花子: {92}点\")\nprint(f\"次郎: {78}点\")\n\n# ✅ DRY準拠（関数にまとめる）\ndef show_score(name, score):\n    print(f\"{name}: {score}点\")\n\nshow_score(\"太郎\", 85)\nshow_score(\"花子\", 92)\nshow_score(\"次郎\", 78)",desc:"「点」を「pts」に変えたくなったら？関数版なら1行の修正で完了！"},{type:"tip",body:"💡 判断基準: 同じパターンが**2回**出たら検討、**3回**以上なら**必ず**関数にする。1回しか使わなくても、名前をつけることで読みやすくなるなら関数化アリ！"}],exercise:{instruction:"show_score(name, score) を作り3人分呼び出してください。",initialCode:"# show_score関数を作ろう\n",expectedOutput:"太郎: 85点\n花子: 92点\n次郎: 78点",keywords:["def","print"],answer:"def show_score(name, score):\n    print(f\"{name}: {score}点\")\nshow_score(\"太郎\", 85)\nshow_score(\"花子\", 92)\nshow_score(\"次郎\", 78)",hints:["def show_score(name, score):","print(f\"{name}: {score}点\")","3回呼び出す"]}}
]},

// ========== 7. オブジェクト指向入門 ==========
{id:"py-oop",title:"オブジェクト指向入門",desc:"クラスと継承。現実世界をコードで表現しよう",level:"i",icon:"🏗️",free:true,nextCourse:"py-janken",lessons:[
{id:"o1",title:"クラスとは？",xp:100,
content:[{type:"text",body:"## <span class=\"term\" data-term=\"class\">クラス</span>って何？🏭\n\nクラスは**設計図**、インスタンスは**設計図から作った実物**。\n\n身近な例で考えよう：\n- 「犬」という概念（名前がある、年齢がある、吠える）→ **クラス**（設計図）\n- あなたの家の「ポチ（3歳）」→ **インスタンス**（実物）\n\n設計図は1つでも、実物は何個でも作れる！"},{type:"code",code:"class Dog:\n    def __init__(self, name, age):\n        self.name = name    # 名前を保存\n        self.age = age      # 年齢を保存\n    \n    def bark(self):\n        return f\"{self.name}「ワン！」\"\n\n# 設計図から2匹の犬を作る\ndog1 = Dog(\"ポチ\", 3)\ndog2 = Dog(\"ハチ\", 5)\nprint(dog1.bark())  # → ポチ「ワン！」",desc:"class = 設計図。Dog(\"ポチ\", 3) = 設計図から実物を作る"},{type:"text",body:"### `__init__` と `self` って何？\n\n- **`__init__`**: 実物を作るときに**自動で呼ばれる**特殊メソッド。初期設定を書く場所。\n- **`self`**: 「**自分自身**」のこと。`self.name = name` は「この犬の名前はnameだよ」って意味。\n\n`Dog(\"ポチ\", 3)` と書くと、裏で `__init__(self, \"ポチ\", 3)` が自動的に呼ばれる。`self` は勝手に入るから書かなくてOK。"},{type:"tip",body:"💡 なぜクラスを使う？ → **関連するデータと動作をまとめられる**から。犬の名前・年齢・吠えるをバラバラの変数と関数にするより、`dog1.name`, `dog1.bark()` とまとまってた方が管理しやすいよね。"}],exercise:{instruction:"Catクラスを作成。describe()で「ミケ は 三毛 色です」と返す。",initialCode:"# Catクラス\n",expectedOutput:"ミケ は 三毛 色です",keywords:["class","def","self"],answer:"class Cat:\n    def __init__(self, name, color):\n        self.name = name\n        self.color = color\n    def describe(self):\n        return f\"{self.name} は {self.color} 色です\"\nprint(Cat(\"ミケ\", \"三毛\").describe())",hints:["class Cat: で定義","__init__ で name, color を保存","describe で f文字列を返す"]}},
{id:"o2",title:"メソッドを使いこなそう",xp:100,
content:[{type:"text",body:"## メソッドを使いこなす！🎮\n\nクラスの中に定義した関数を**メソッド**って呼ぶ。「そのモノができること」を表す。\n\n- 犬.吠える() → `dog.bark()`\n- 銀行口座.入金する(1000) → `account.deposit(1000)`\n- カウンター.増やす() → `counter.add()`\n\n第1引数は必ず `self`（自分自身）だけど、呼ぶときは省略できる。"},{type:"code",code:"class BankAccount:\n    def __init__(self):\n        self.balance = 0     # 残高0で開始\n    \n    def deposit(self, amount):\n        self.balance += amount   # 入金\n    \n    def show(self):\n        print(f\"残高: {self.balance}円\")\n\nacc = BankAccount()\nacc.deposit(1000)\nacc.show()   # → 残高: 1000円",desc:"deposit()で残高が変わる。show()で確認する。"},{type:"text",body:"### 属性とメソッドの関係\n\n- **属性（データ）**: `self.balance` → 口座が持ってるデータ\n- **メソッド（動作）**: `deposit()`, `show()` → 口座ができること\n\nメソッドを通じて属性を安全に操作する。直接 `acc.balance = -9999` と書けちゃうけど、メソッド経由にすれば「残高が負になるのを防ぐ」チェックを入れられる。"},{type:"tip",body:"💡 `acc.deposit(1000)` で呼ぶけど、定義は `def deposit(self, amount):`。呼ぶときに `self` を書かないのは、Pythonが自動で `acc` を `self` に入れてくれるから。"}],exercise:{instruction:"BankAccountクラス。初期残高0、deposit(amount)で入金、show()で残高表示。1000円入金。",initialCode:"# BankAccount\n",expectedOutput:"残高: 1000円",keywords:["class","def","self"],answer:"class BankAccount:\n    def __init__(self):\n        self.balance = 0\n    def deposit(self, amount):\n        self.balance += amount\n    def show(self):\n        print(f\"残高: {self.balance}円\")\nacc = BankAccount()\nacc.deposit(1000)\nacc.show()",hints:["__init__ で self.balance = 0","deposit で self.balance += amount","show で残高を表示"]}},
{id:"o3",title:"継承",xp:110,
content:[{type:"text",body:"## 継承 - クラスを拡張！🧬\n\n**親クラス**（ベース）を元に、**子クラス**（派生）を作れる。これが**継承**。\n\nイメージ：\n- 「動物」（名前がある）→ 親\n- 「犬」（動物 + 吠える）→ 子\n- 「猫」（動物 + 鳴く）→ 子\n\n子は親の機能を**全部引き継ぎ**つつ、**独自の機能を追加**できる！"},{type:"code",code:"class Animal:\n    def __init__(self, name):\n        self.name = name\n\nclass Dog(Animal):       # Animalを継承！\n    def speak(self):\n        return f\"{self.name}「ワン！」\"\n\nclass Cat(Animal):       # Animalを継承！\n    def speak(self):\n        return f\"{self.name}「ニャー！」\"\n\nfor a in [Dog(\"ポチ\"), Cat(\"タマ\")]:\n    print(a.speak())",desc:"Dog(Animal)と書くだけで、Animalの機能を全部引き継ぐ"},{type:"text",body:"### super() で親の処理を呼ぶ\n\n子クラスで `__init__` を上書きするとき、親の `__init__` も実行したいなら **`super().__init__()`** を使う：\n\n<span class=\"copyable\">class Circle(Shape):</span>\n<span class=\"copyable\">    def __init__(self, name, radius):</span>\n<span class=\"copyable\">        super().__init__(name)  # 親のinit</span>\n<span class=\"copyable\">        self.radius = radius   # 子だけの属性</span>"},{type:"tip",body:"💡 継承を使うべき場面 → **「AはBの一種である」**と言えるとき。「犬は動物の一種」→ OK ✅。「車はエンジンの一種」→ NG ❌（車はエンジンを**持っている**）。"}],exercise:{instruction:"Shape(name)、Circle(name, radius)を作り、area()で面積(3.14*r**2)を返す。",initialCode:"# Shape, Circle\n",expectedOutput:"円\n78.5",keywords:["class","def"],answer:"class Shape:\n    def __init__(self, name):\n        self.name = name\nclass Circle(Shape):\n    def __init__(self, name, radius):\n        super().__init__(name)\n        self.radius = radius\n    def area(self):\n        return 3.14 * self.radius ** 2\nc = Circle(\"円\", 5)\nprint(c.name)\nprint(c.area())",hints:["class Circle(Shape): で継承","super().__init__(name)","3.14 * self.radius ** 2"]}}
]},

// ========== 8. エラーと友達になろう ==========
{id:"py-error",title:"エラーと友達になろう",desc:"エラーメッセージの読み方・try/except・デバッグのコツ",level:"i",icon:"🛡️",free:true,nextCourse:"py-oop",lessons:[
{id:"e1",title:"エラーメッセージを読もう",xp:80,
content:[{type:"text",body:"## エラーは怖くない！🛡️\n\nプロのエンジニアでも毎日何十回とエラーを出す。エラーは「失敗」じゃなくて、**Pythonからのヒント**だよ。\n\n### よく出るエラー TOP5\n\n| エラー | 意味 | あるある |\n|---|---|---|\n| SyntaxError | 書き方が変 | カッコ閉じ忘れ |\n| NameError | その名前知らない | `pritn` ← typo |\n| TypeError | 型が合わない | `\"3\" + 5` |\n| IndexError | 範囲外 | リストの外にアクセス |\n| ValueError | 値が不正 | `int(\"abc\")` |"},{type:"code",code:"name = \"太郎\"\nage = 25\n\n# ❌ TypeError: str + int はダメ！\n# print(\"年齢: \" + age)\n\n# ✅ 対処法: f文字列を使う！\nprint(f\"年齢: {age}\")",desc:"文字列+数字はエラー。f文字列なら型を気にしなくてOK"},{type:"text",body:"### エラーメッセージの読み方\n\nエラーが出たら**最後の行**を読もう。答えが書いてある！\n\n```\nTraceback (most recent call last):\n  File \"test.py\", line 3    ← 3行目でエラー\nTypeError: can only...       ← strとintは足せないよ\n```\n\n**初心者の80%のエラーはこの3つ**:\n1. スペルミス（`pritn` → `print`）\n2. カッコ/クォート閉じ忘れ\n3. インデントずれ"},{type:"tip",body:"💡 エラーメッセージをそのまま**Googleにコピペ**すると、だいたい解決策が見つかる。プロも毎日やってる技だよ！"}],exercise:{instruction:"文字列 \"100\" と数字 50 を足して 150 を表示してください。",initialCode:"# 型変換でエラーを避ける\n",expectedOutput:"150",keywords:["int","print"],answer:"a = \"100\"\nprint(int(a) + 50)",hints:["\"100\" は文字列","int() で変換","print(int(\"100\") + 50)"]}},
{id:"e2",title:"try/except",xp:90,
content:[{type:"text",body:"## try/except - エラーを捕まえる！🎣\n\nユーザーが「数字を入力して」と言われても `abc` と入力するかもしれない。そのときプログラムが**クラッシュしない**ようにするのが `try/except`！\n\nイメージ：\n- `try:` → 「これやってみて」\n- `except:` → 「もしダメだったら、代わりにこっち」"},{type:"code",code:"# エラーが起きそうなコードをtryの中に\ntry:\n    result = int(\"abc\")    # ← これはエラーになる\nexcept ValueError:\n    print(\"数字を入力してね！\")\n# → プログラムは止まらず「数字を入力してね！」と表示",desc:"tryの中でエラー → exceptにジャンプ。プログラムは止まらない！"},{type:"text",body:"### 実用パターン\n\n数字っぽい文字列をループで変換する場面：\n\n<span class=\"copyable\">for item in [\"10\", \"abc\", \"30\"]:</span>\n<span class=\"copyable\">    try:</span>\n<span class=\"copyable\">        total += int(item)</span>\n<span class=\"copyable\">    except ValueError:</span>\n<span class=\"copyable\">        pass  # 変換できないものはスキップ</span>\n\n`pass` は「何もしない」という意味。エラーを無視してスキップしたいときに使う。"},{type:"tip",body:"💡 `except:` だけ（エラー名なし）は全部キャッチするけど、バグを隠しちゃうから避けよう。**何のエラーを想定してるか**を書く（`except ValueError:` など）のがプロの作法。"}],exercise:{instruction:"[\"10\",\"abc\",\"30\"]をループし、int()変換できた数字の合計を表示。",initialCode:"# 合計を求める\n",expectedOutput:"40",keywords:["try","except","print"],answer:"total = 0\nfor item in [\"10\", \"abc\", \"30\"]:\n    try:\n        total += int(item)\n    except ValueError:\n        pass\nprint(total)",hints:["total = 0 で初期化","try: total += int(item)","except ValueError: pass"]}},
{id:"e3",title:"デバッグのコツ",xp:90,
content:[{type:"text",body:"## デバッグのコツ 🔍\n\nバグ（不具合）を見つけて直す作業を**デバッグ**って呼ぶ。\n\n### 最強のデバッグ法: print文デバッグ\n\n怪しい場所に `print()` を入れて、変数の中身を確認する。シンプルだけど**プロも毎日やってる**方法。\n\n**3ステップ:**\n1. 🔄 **再現**: どうやったらバグが出る？\n2. 🎯 **特定**: どの行が原因？ → print()で探る\n3. 🔧 **修正**: 直して再テスト"},{type:"code",code:"scores = [10, 20, 30, 40, 50]\n\n# print文デバッグ: 途中経過を確認！\ntotal = sum(scores)\nprint(f\"DEBUG: total = {total}\")   # 150\n\ncount = len(scores)\nprint(f\"DEBUG: count = {count}\")   # 5\n\naverage = total / count\nprint(f\"平均: {average}\")           # 30.0",desc:"怪しい変数にprint()を挟んで中身を確認する"},{type:"text",body:"### よくあるバグ\n\n| バグ | 原因 | 対策 |\n|---|---|---|\n| 計算がおかしい | 演算子の優先順位 | カッコ()をつける |\n| 条件が効かない | `=` と `==` の間違い | if文の前にprint |\n| リストが空 | append忘れ | ループ内でprint |\n| 無限ループ | 終了条件ミス | カウンタをprint |"},{type:"tip",body:"💡 デバッグ終わったら**print文を消す**のを忘れずに！ 消し忘れ防止に `print(f\"DEBUG: {変数}\")` と `DEBUG:` をつけておくと、あとで検索して消しやすい。"}],exercise:{instruction:"リスト [10, 20, 30, 40, 50] の平均値を計算して表示。",initialCode:"# 平均値を計算\n",expectedOutput:"30.0",keywords:["sum","len","print"],answer:"scores = [10, 20, 30, 40, 50]\naverage = sum(scores) / len(scores)\nprint(average)",hints:["sum() で合計","len() で要素数","合計÷要素数=平均"]}}
]},

// ========== 9. エディタショートカット マスター ==========
{id:"shortcut-master",title:"エディタショートカット マスター",desc:"VS Code (Windows) の必須ショートカットで作業効率10倍",level:"s",icon:"⌨️",free:true,lessons:[
{id:"sc1",title:"保存・元に戻す・やり直し",xp:40,
content:[{type:"text",body:"## まず覚える3つ ⌨️\n\nショートカットキーを使うとマウスに手を伸ばす回数が激減する。**コーディング速度が2〜3倍**になるよ。\n\nまずはこの3つだけ！\n\n| 操作 | キー | 覚え方 |\n|---|---|---|\n| 保存 | **Ctrl+S** | **S**ave |\n| 元に戻す | **Ctrl+Z** | 時間を**Z**（戻）す |\n| やり直し | **Ctrl+Y** | **Y**（やり）直し |\n\nこの3つは**Word、Excel、ブラウザ…どこでも使える**共通ショートカット！"},{type:"code",code:"shortcuts = {\n    \"保存\": \"Ctrl+S\",\n    \"元に戻す\": \"Ctrl+Z\",\n    \"やり直し\": \"Ctrl+Y\"\n}\nfor action, key in shortcuts.items():\n    print(f\"{action}: {key}\")",desc:"辞書とループの復習にもなるよ！"},{type:"tip",body:"💡 **Ctrl+Sは5分に1回押す癖をつけよう。** 保存してないファイルが消える悲劇は、この習慣だけで防げる。プロは無意識に指が勝手にCtrl+Sを押してるよ。"}],exercise:{instruction:"変数 shortcut に \"Ctrl+S\" を代入し「保存: Ctrl+S」と表示。",initialCode:"# ショートカット\n",expectedOutput:"保存: Ctrl+S",keywords:["print"],answer:"shortcut = \"Ctrl+S\"\nprint(f\"保存: {shortcut}\")",hints:["shortcut = \"Ctrl+S\"","f文字列で表示"]}},
{id:"sc2",title:"カーソル移動と選択",xp:40,
content:[{type:"text",body:"## カーソル高速移動 🏃\n\n矢印キーで1文字ずつ移動するのは遅い！ 以下のキーで**一気にジャンプ**できる。\n\n| 操作 | キー |\n|---|---|\n| 行の先頭へ | **Home** |\n| 行の末尾へ | **End** |\n| 単語ごとに移動 | **Ctrl+←/→** |\n| 行選択 | **Shift+↓/↑** |\n| 単語選択 | **Ctrl+Shift+←/→** |\n\n**Shiftキー**を押しながら移動すると、動いた範囲が**選択**される！"},{type:"code",code:"sc = {\n    \"行頭\": \"Home\",\n    \"行末\": \"End\",\n    \"単語移動\": \"Ctrl+矢印\"\n}\nfor k, v in sc.items():\n    print(f\"{k}: {v}\")",desc:"辞書の items() でキーと値を同時にループ"},{type:"tip",body:"💡 **Home → Shift+End** で「行全体を選択」。行をまるごとコピー・削除したいときに超便利。マウスでドラッグするより10倍速い！"}],exercise:{instruction:"辞書にショートカットを格納しループで表示。",initialCode:"# ショートカット辞書\n",expectedOutput:"行頭: Home\n行末: End\n単語移動: Ctrl+矢印",keywords:["for","print"],answer:"sc = {\"行頭\": \"Home\", \"行末\": \"End\", \"単語移動\": \"Ctrl+矢印\"}\nfor k, v in sc.items():\n    print(f\"{k}: {v}\")",hints:["辞書を作成","for k, v in sc.items():","print(f\"{k}: {v}\")"]}},
{id:"sc3",title:"コピー・切り取り・行操作",xp:50,
content:[{type:"text",body:"## コピー・切り取り・行操作 ✂️\n\n| 操作 | キー |\n|---|---|\n| コピー | **Ctrl+C** |\n| 切り取り | **Ctrl+X** |\n| 貼り付け | **Ctrl+V** |\n\n### VS Code限定の行操作\n\n| 操作 | キー |\n|---|---|\n| 行を複製 | **Ctrl+Shift+D** |\n| 行を上下に移動 | **Alt+↑/↓** |\n| 行を削除 | **Ctrl+Shift+K** |\n\n特に **Alt+↑↓** は行の並べ替えに最強！"},{type:"code",code:"keys = [\"Ctrl+C\", \"Ctrl+X\", \"Ctrl+V\"]\nfor i, key in enumerate(keys, 1):\n    print(f\"{i}. {key}\")",desc:"enumerate(list, 1) で1から番号をつけてループ"},{type:"tip",body:"💡 VS Codeで**何も選択せずにCtrl+C**を押すと、行全体がコピーされる。わざわざ行を選択する手間が省ける超便利機能！"}],exercise:{instruction:"リスト[\"Ctrl+C\",\"Ctrl+X\",\"Ctrl+V\"]を番号付きで表示。",initialCode:"# 番号付き表示\n",expectedOutput:"1. Ctrl+C\n2. Ctrl+X\n3. Ctrl+V",keywords:["for","enumerate","print"],answer:"keys = [\"Ctrl+C\", \"Ctrl+X\", \"Ctrl+V\"]\nfor i, k in enumerate(keys, 1):\n    print(f\"{i}. {k}\")",hints:["enumerate(list, 1)","for i, k in enumerate(...):"]}},
{id:"sc4",title:"検索・置換・マルチカーソル",xp:50,
content:[{type:"text",body:"## 検索・置換・マルチカーソル 🔎\n\n| 操作 | キー |\n|---|---|\n| 検索 | **Ctrl+F** |\n| 置換 | **Ctrl+H** |\n| 同じ単語を追加選択 | **Ctrl+D** |\n\n### Ctrl+D が最強\n\n変数名を一括変更したいとき、Ctrl+Dを**連打**すると同じ単語が次々と選択される。そのまま入力すれば**全部同時に書き換わる**！\n\n手動で1つずつ直すのとは次元が違う。"},{type:"code",code:"text = \"user_name, user_age, user_email\"\n\n# Pythonのreplace()も「置換」の一種\nresult = text.replace(\"user\", \"customer\")\nprint(result)\n# → customer_name, customer_age, customer_email",desc:".replace()は文字列中のすべてを一括置換"},{type:"tip",body:"💡 Ctrl+Hの置換画面で**正規表現（Regex）**をONにすると、パターンで一括置換もできる。今は知らなくてOKだけど、いずれ強力な武器になるよ。"}],exercise:{instruction:"文字列の\"user\"を全て\"customer\"に置換して表示。",initialCode:"# 一括置換\n",expectedOutput:"customer_name, customer_age, customer_email",keywords:["replace","print"],answer:"text = \"user_name, user_age, user_email\"\nprint(text.replace(\"user\", \"customer\"))",hints:["text = \"user_name, ...\"",".replace(\"user\", \"customer\")"]}},
{id:"sc5",title:"TOP10まとめ",xp:60,
content:[{type:"text",body:"## TOP 10 まとめ 🏆\n\nまずはTOP5を体に染み込ませよう！\n\n**絶対覚える（TOP5）:**\n1. **Ctrl+S** — 保存（5分に1回！）\n2. **Ctrl+Z** — 元に戻す\n3. **Ctrl+C/X/V** — コピー/切り取り/貼り付け\n4. **Ctrl+D** — 同じ単語選択（変数名一括変更）\n5. **Ctrl+F** — 検索\n\n**余裕が出たら（6-10）:**\n6. Ctrl+H — 置換\n7. Ctrl+P — ファイルを素早く開く\n8. Ctrl+Shift+P — コマンドパレット\n9. Ctrl+/ — コメント切替\n10. Alt+↑↓ — 行の上下移動"},{type:"code",code:"top = [\n    (\"Ctrl+S\", \"保存\"),\n    (\"Ctrl+Z\", \"元に戻す\"),\n    (\"Ctrl+C\", \"コピー\"),\n    (\"Ctrl+X\", \"切り取り\"),\n    (\"Ctrl+V\", \"貼り付け\"),\n    (\"Ctrl+D\", \"同じ単語選択\"),\n    (\"Ctrl+F\", \"検索\"),\n    (\"Ctrl+H\", \"置換\"),\n    (\"Ctrl+P\", \"ファイルを開く\"),\n    (\"Ctrl+/\", \"コメント切替\")\n]\nfor i, (key, desc) in enumerate(top, 1):\n    print(f\"{i}. {key} - {desc}\")",desc:"タプルのリスト + enumerate + アンパック（分解代入）"},{type:"tip",body:"💡 **全部一気に覚えようとしない**のがコツ。まずCtrl+S, Ctrl+Z, Ctrl+C/Vだけ意識して使う。慣れたらCtrl+D, Ctrl+Fを追加。1ヶ月後には全部使えてるよ。"}],exercise:{instruction:"TOP10をenumerate()で表示。",initialCode:"# TOP 10\n",expectedOutput:"1. Ctrl+S - 保存\n2. Ctrl+Z - 元に戻す\n3. Ctrl+C - コピー\n4. Ctrl+X - 切り取り\n5. Ctrl+V - 貼り付け\n6. Ctrl+D - 同じ単語選択\n7. Ctrl+F - 検索\n8. Ctrl+H - 置換\n9. Ctrl+P - ファイルを開く\n10. Ctrl+/ - コメント切替",keywords:["for","enumerate","print"],answer:"top = [(\"Ctrl+S\",\"保存\"),(\"Ctrl+Z\",\"元に戻す\"),(\"Ctrl+C\",\"コピー\"),(\"Ctrl+X\",\"切り取り\"),(\"Ctrl+V\",\"貼り付け\"),(\"Ctrl+D\",\"同じ単語選択\"),(\"Ctrl+F\",\"検索\"),(\"Ctrl+H\",\"置換\"),(\"Ctrl+P\",\"ファイルを開く\"),(\"Ctrl+/\",\"コメント切替\")]\nfor i,(k,d) in enumerate(top,1):\n    print(f\"{i}. {k} - {d}\")",hints:["タプルのリストを作成","enumerate(top, 1)"]}}
]},

// ========== 10. ミニゲーム (PRO) ==========
{id:"py-game",title:"Pythonでミニゲーム作り",desc:"じゃんけん・数当て・クイズ。楽しみながら実力アップ",level:"i",icon:"🎮",free:false,lessons:[
{id:"g1",title:"じゃんけんゲーム",xp:100,
content:[{type:"text",body:"## じゃんけんゲーム\n\nrandomモジュールでランダムな手を出させます。"},{type:"code",code:"import random\nhands = [\"グー\", \"チョキ\", \"パー\"]\nplayer = \"グー\"\ncomputer = random.choice(hands)\nprint(f\"あなた: {player}\")\nprint(f\"PC: {computer}\")",desc:"じゃんけんゲーム"}],exercise:{instruction:"random.choice()で色を選んで表示。",initialCode:"import random\n",expectedOutput:"",keywords:["random.choice","print"],answer:"import random\ncolor = random.choice([\"赤\", \"青\", \"緑\"])\nprint(color)",hints:["random.choice([...])","print(color)"]}},
{id:"g2",title:"数当てゲーム",xp:110,
content:[{type:"text",body:"## 数当てゲーム"},{type:"code",code:"import random\nanswer = random.randint(1, 10)\nguess = 5\nif guess == answer:\n    print(\"正解！\")\nelse:\n    print(f\"答えは{answer}でした\")",desc:"数当てゲーム"}],exercise:{instruction:"random.randint(1,10)で数字を生成し表示。",initialCode:"import random\n",expectedOutput:"",keywords:["random.randint","print"],answer:"import random\nnum = random.randint(1, 10)\nprint(f\"答えは{num}です\")",hints:["random.randint(1, 10)"]}},
{id:"g3",title:"クイズアプリ",xp:120,
content:[{type:"text",body:"## クイズアプリ"},{type:"code",code:"quizzes = [\n    {\"q\": \"Pythonの作者は？\", \"a\": \"グイド\"},\n    {\"q\": \"print()は何をする？\", \"a\": \"表示\"},\n]\nscore = 0\nfor quiz in quizzes:\n    score += 1\nprint(f\"スコア: {score}/{len(quizzes)}\")",desc:"クイズ"}],exercise:{instruction:"3問のクイズスコアを表示。",initialCode:"# クイズ\n",expectedOutput:"3問中3問正解！",keywords:["for","print"],answer:"quizzes = [{\"q\":\"1+1=\",\"a\":2},{\"q\":\"2*3=\",\"a\":6},{\"q\":\"10//3=\",\"a\":3}]\nscore = 0\nfor q in quizzes:\n    score += 1\nprint(f\"{len(quizzes)}問中{score}問正解！\")",hints:["辞書リスト","forでループ"]}}
]},

// ========== 11. Webスクレイピング (PRO) ==========
{id:"py-scraping",title:"Webスクレイピング入門",desc:"Webからデータを自動取得する基礎を学ぼう",level:"a",icon:"🌐",free:false,lessons:[
{id:"w1",title:"HTMLの基本",xp:100,
content:[{type:"text",body:"## HTMLとは？\n\nWebページはHTMLで書かれています。"},{type:"code",code:"html = '<h1>PyMasters</h1>'\ntitle_start = html.find('<h1>') + 4\ntitle_end = html.find('</h1>')\nprint(html[title_start:title_end])",desc:"HTMLからデータ取り出し"}],exercise:{instruction:"<title>PyMasters</title>からタイトルを取り出して表示。",initialCode:"html = '<title>PyMasters</title>'\n",expectedOutput:"PyMasters",keywords:["find","print"],answer:"html = '<title>PyMasters</title>'\nstart = html.find('<title>') + 7\nend = html.find('</title>')\nprint(html[start:end])",hints:["find()で位置を探す","スライスで切り出す"]}},
{id:"w2",title:"データ取得の仕組み",xp:110,
content:[{type:"text",body:"## requestsライブラリ\n\nHTTPステータスコードの概念を学びましょう。"},{type:"code",code:"status_code = 200\nif status_code == 200:\n    print(\"ページ取得成功！\")",desc:"HTTPステータスコード"}],exercise:{instruction:"status=404で判定。404なら「ページが見つかりません」。",initialCode:"# ステータスコード判定\n",expectedOutput:"ページが見つかりません",keywords:["if","elif","print"],answer:"status = 404\nif status == 200:\n    print(\"成功\")\nelif status == 404:\n    print(\"ページが見つかりません\")\nelse:\n    print(\"エラー\")",hints:["if status == 200:","elif status == 404:"]}},
{id:"w3",title:"データを抽出しよう",xp:120,
content:[{type:"text",body:"## データ抽出"},{type:"code",code:"html_items = [\n    '<li>りんご 100円</li>',\n    '<li>バナナ 200円</li>',\n]\nfor item in html_items:\n    start = item.find('>') + 1\n    end = item.find('</li>')\n    print(item[start:end])",desc:"複数アイテムから抽出"}],exercise:{instruction:"['<p>Hello</p>','<p>World</p>','<p>Python</p>']からテキストを抽出。",initialCode:"html_items = ['<p>Hello</p>', '<p>World</p>', '<p>Python</p>']\n",expectedOutput:"Hello\nWorld\nPython",keywords:["for","print"],answer:"html_items = ['<p>Hello</p>', '<p>World</p>', '<p>Python</p>']\nfor item in html_items:\n    start = item.find('>') + 1\n    end = item.find('</p>')\n    print(item[start:end])",hints:["find('>') + 1","find('</p>')"]}}
]},

// ========== 12. Python自動化 (PRO) ==========
{id:"py-auto",title:"Python自動化入門",desc:"ファイル操作・テキスト処理・レポート生成を自動化",level:"a",icon:"🤖",free:false,lessons:[
{id:"a1",title:"テキスト処理の基本",xp:100,
content:[{type:"text",body:"## テキスト処理\n\nsplit()で分割、join()で結合。"},{type:"code",code:"csv_line = \"太郎,25,東京\"\nparts = csv_line.split(\",\")\nprint(f\"名前: {parts[0]}\")",desc:"split()で分割"}],exercise:{instruction:"\"Python-Java-JavaScript\"を\"-\"で分割し各言語を表示。",initialCode:"# 分割して表示\n",expectedOutput:"Python\nJava\nJavaScript",keywords:["split","for","print"],answer:"text = \"Python-Java-JavaScript\"\nfor lang in text.split(\"-\"):\n    print(lang)",hints:["split(\"-\")","for lang in ..."]}},
{id:"a2",title:"データの集計・変換",xp:110,
content:[{type:"text",body:"## データ集計"},{type:"code",code:"sales = [1200, 3400, 2800, 5100, 1900]\nprint(f\"合計: {sum(sales)}円\")\nprint(f\"平均: {sum(sales)//len(sales)}円\")",desc:"組み込み関数で集計"}],exercise:{instruction:"scores = [85, 92, 78, 95, 88] の合計、平均、最高点を表示。",initialCode:"scores = [85, 92, 78, 95, 88]\n",expectedOutput:"合計: 438\n平均: 87.6\n最高: 95",keywords:["sum","max","print"],answer:"scores = [85, 92, 78, 95, 88]\nprint(f\"合計: {sum(scores)}\")\nprint(f\"平均: {sum(scores)/len(scores)}\")\nprint(f\"最高: {max(scores)}\")",hints:["sum()","max()"]}},
{id:"a3",title:"レポート自動生成",xp:120,
content:[{type:"text",body:"## レポート自動生成"},{type:"code",code:"def generate_report(title, data):\n    print(f\"=== {title} ===\")\n    print(f\"合計: {sum(data)}\")\n    print(f\"平均: {sum(data)/len(data):.1f}\")\n\ngenerate_report(\"月間売上\", [12000, 34000, 28000, 51000])",desc:"関数でレポート生成"}],exercise:{instruction:"generate_report(title, numbers)を作り呼び出し。",initialCode:"# レポート関数\n",expectedOutput:"=== テスト結果 ===\n合計: 240\n平均: 80.0",keywords:["def","print","sum"],answer:"def generate_report(title, numbers):\n    print(f\"=== {title} ===\")\n    print(f\"合計: {sum(numbers)}\")\n    print(f\"平均: {sum(numbers)/len(numbers)}\")\ngenerate_report(\"テスト結果\", [80, 90, 70])",hints:["def generate_report(title, numbers):","sum() と len()"]}}
]},

// ========== 13. じゃんけんゲームを作ろう ==========
{id:"py-janken",title:"じゃんけんゲームを作ろう",desc:"randomモジュールとif文を組み合わせて、じゃんけんゲームを完成させよう！",level:"s",icon:"🎮",free:true,nextCourse:"py-calc",lessons:[
{id:"jk1",title:"randomモジュールの使い方",xp:60,
content:[{type:"text",body:"## ランダムに手を選ぶ！🎲\n\nじゃんけんゲームを作るには、CPUがランダムに手を出す必要があるよね。\n\nそこで使うのが **`random`モジュール**。Pythonに最初から入ってる「ランダム関連の道具箱」だよ。\n\n### 使い方は2ステップ\n1. `import random` — 道具箱を持ってくる\n2. `random.choice(リスト)` — リストからランダムに1つ選ぶ"},{type:"code",code:"import random\nhands = [\"グー\", \"チョキ\", \"パー\"]\n\n# ランダムに1つ選ぶ（実行するたび変わる！）\ncpu_hand = random.choice(hands)\nprint(f\"CPUの手: {cpu_hand}\")",desc:"random.choice()はリストからランダムに1つ返す"},{type:"text",body:"### リストのインデックスでも取り出せる\n\n<span class=\"copyable\">hands[0]</span> → グー\n<span class=\"copyable\">hands[1]</span> → チョキ\n<span class=\"copyable\">hands[2]</span> → パー\n\n`random.choice(hands)` は内部的に「0〜2のどれかを選んで、hands[その番号]を返す」っていう動き。"},{type:"tip",body:"💡 `import` は「モジュールを使うよ！」とPythonに宣言すること。ファイルの一番上に書くのがお作法。randomの他にも `math`, `datetime`, `os` など便利なモジュールがたくさんあるよ。"}],exercise:{instruction:"handsリスト [\"グー\", \"チョキ\", \"パー\"] を作り、\nrandom.choice(hands)でcpu_handに代入し、\nprint(f\"選択肢: {hands}\") と print(f\"CPUの手: {cpu_hand}\") を表示してください。\n※ 2行目はランダムなので何が出てもOK！（1行目だけで採点します）",initialCode:"import random\n",expectedOutput:"選択肢: ['グー', 'チョキ', 'パー']",keywords:["random.choice","hands","print"],answer:"import random\nhands = [\"グー\", \"チョキ\", \"パー\"]\ncpu_hand = random.choice(hands)\nprint(f\"選択肢: {hands}\")",hints:["hands = [\"グー\", \"チョキ\", \"パー\"]","random.choice(hands)でランダム選択","print(f\"選択肢: {hands}\")"]}},
{id:"jk2",title:"勝敗判定ロジック",xp:70,
content:[{type:"text",body:"## 勝敗を判定しよう！⚔️\n\nじゃんけんの勝敗ルール：\n\n| プレイヤー | CPU | 結果 |\n|---|---|---|\n| グー | チョキ | **勝ち** ✊>✌️ |\n| チョキ | パー | **勝ち** ✌️>✋ |\n| パー | グー | **勝ち** ✋>✊ |\n| 同じ手 | — | **あいこ** |\n| それ以外 | — | **負け** |\n\nこれをif/elif/elseで書くだけ！"},{type:"code",code:"player = \"グー\"\ncpu = \"チョキ\"\n\nif player == cpu:\n    print(\"あいこ！\")\nelif (player==\"グー\" and cpu==\"チョキ\") or \\\n     (player==\"チョキ\" and cpu==\"パー\") or \\\n     (player==\"パー\" and cpu==\"グー\"):\n    print(\"あなたの勝ち！\")\nelse:\n    print(\"あなたの負け…\")",desc:"勝ちパターン3つを or でつなぐ。あいこ→勝ち→それ以外は負け"},{type:"text",body:"### ポイント\n\n- まず**あいこ**を判定（一番シンプル: `player == cpu`）\n- 次に**勝ちパターン3つ**を `or` でつなぐ\n- 残りは全部**負け** → `else` でOK\n\n`\\` は「この行、次の行に続くよ」というマーク。長い行を見やすく改行するために使う。"},{type:"tip",body:"💡 負けパターンを書く必要がないのがポイント。「あいこでも勝ちでもない → 負け」と `else` で受ける。全パターン書くと6パターンになって大変だけど、この書き方なら3パターンで済む！"}],exercise:{instruction:"player=\"パー\", cpu=\"グー\"で勝敗判定。",initialCode:"player = \"パー\"\ncpu = \"グー\"\n",expectedOutput:"あなたの勝ち！",keywords:["if","print"],answer:"player = \"パー\"\ncpu = \"グー\"\nif player == cpu:\n    print(\"あいこ！\")\nelif (player==\"グー\" and cpu==\"チョキ\") or (player==\"チョキ\" and cpu==\"パー\") or (player==\"パー\" and cpu==\"グー\"):\n    print(\"あなたの勝ち！\")\nelse:\n    print(\"あなたの負け…\")",hints:["player == cpu であいこ","勝つパターンを or でつなぐ"]}},
{id:"jk3",title:"関数にまとめる",xp:80,
content:[{type:"text",body:"## 関数にまとめよう！📦\n\n前のレッスンの判定ロジックを `judge(player, cpu)` という関数にまとめると：\n\n- 何度でも呼び出せる（3回勝負、100回勝負にも対応）\n- テストしやすい（引数を変えるだけ）\n- コードが読みやすい（`judge(\"グー\", \"チョキ\")` → 一目でわかる）\n\n### print → return に変更\n\n前回は `print(\"勝ち\")` だったけど、今回は **`return \"勝ち\"`** に。結果を**返す**ことで、あとから使い回せる！"},{type:"code",code:"def judge(player, cpu):\n    if player == cpu:\n        return \"あいこ\"\n    elif (player==\"グー\" and cpu==\"チョキ\") or \\\n         (player==\"チョキ\" and cpu==\"パー\") or \\\n         (player==\"パー\" and cpu==\"グー\"):\n        return \"勝ち\"\n    else:\n        return \"負け\"\n\nprint(judge(\"グー\", \"チョキ\"))  # → 勝ち",desc:"returnで結果を返すと、あとから使える"},{type:"text",body:"### print vs return\n\n- `print(\"勝ち\")` → 画面に表示して終わり。結果を使い回せない。\n- `return \"勝ち\"` → 結果を**返す**。変数に入れて後で使える。\n\n<span class=\"copyable\">result = judge(\"グー\", \"チョキ\")</span>\n<span class=\"copyable\">if result == \"勝ち\": wins += 1</span>  ← こういう使い方ができる！"},{type:"tip",body:"💡 関数を作ったら**全パターンをテスト**する習慣をつけよう。じゃんけんなら9通り（3×3）。バグを見つけるのは「リリース後」より「テスト中」の方が100倍楽！"}],exercise:{instruction:"judge関数でjudge(\"チョキ\",\"パー\")を表示。",initialCode:"# judge関数\n",expectedOutput:"勝ち",keywords:["def","judge","return","print"],answer:"def judge(player, cpu):\n    if player == cpu: return \"あいこ\"\n    elif (player==\"グー\" and cpu==\"チョキ\") or (player==\"チョキ\" and cpu==\"パー\") or (player==\"パー\" and cpu==\"グー\"): return \"勝ち\"\n    else: return \"負け\"\nprint(judge(\"チョキ\", \"パー\"))",hints:["def judge(player, cpu):","return で結果を返す"]}},
{id:"jk4",title:"3回勝負",xp:90,
content:[{type:"text",body:"## 3回勝負で完成！🎮\n\n最後の仕上げ。`for` ループで3回じゃんけんして、勝利数をカウントしよう。\n\nこのレッスンでは結果が毎回同じになるように、CPUの手を**事前に決めて**おくよ。実際のゲームでは `random.choice()` を使えばランダムになる！\n\n### やること\n1. 自分の手とCPUの手を用意\n2. for文で3回ループ\n3. 各回の結果を表示\n4. 勝利数を集計"},{type:"code",code:"def judge(p, c):\n    if p == c: return \"あいこ\"\n    elif (p==\"グー\" and c==\"チョキ\") or \\\n         (p==\"チョキ\" and c==\"パー\") or \\\n         (p==\"パー\" and c==\"グー\"): return \"勝ち\"\n    else: return \"負け\"\n\nmy_hands = [\"グー\", \"パー\", \"チョキ\"]\ncpu_hands = [\"チョキ\", \"パー\", \"グー\"]\nwins = 0\n\nfor i in range(3):\n    result = judge(my_hands[i], cpu_hands[i])\n    print(f\"{i+1}回目: {my_hands[i]} vs {cpu_hands[i]} → {result}\")\n    if result == \"勝ち\": wins += 1\n\nprint(f\"勝利数: {wins}/3\")",desc:"for + judge関数 + カウンタで3回勝負が完成！"},{type:"tip",body:"💡 ゲームとして完成させるなら、my_handsもrandom.choice()にして、while文で「もう1回やる？」と聞くループを追加してみよう。このコースで学んだことの総まとめになるよ！"}],exercise:{instruction:"judge関数を使い3回勝負。\n自分の手: [\"グー\", \"パー\", \"チョキ\"]\nCPUの手: [\"チョキ\", \"パー\", \"グー\"]\n各回の結果と勝利数を表示。",initialCode:"def judge(p, c):\n    if p == c: return \"あいこ\"\n    elif (p==\"グー\" and c==\"チョキ\") or (p==\"チョキ\" and c==\"パー\") or (p==\"パー\" and c==\"グー\"): return \"勝ち\"\n    else: return \"負け\"\nmy_hands = [\"グー\", \"パー\", \"チョキ\"]\ncpu_hands = [\"チョキ\", \"パー\", \"グー\"]\nwins = 0\n",expectedOutput:"1回目: グー vs チョキ → 勝ち\n2回目: パー vs パー → あいこ\n3回目: チョキ vs グー → 負け\n勝利数: 1/3",keywords:["for","judge","print"],answer:"def judge(p, c):\n    if p == c: return \"あいこ\"\n    elif (p==\"グー\" and c==\"チョキ\") or (p==\"チョキ\" and c==\"パー\") or (p==\"パー\" and c==\"グー\"): return \"勝ち\"\n    else: return \"負け\"\nmy_hands = [\"グー\", \"パー\", \"チョキ\"]\ncpu_hands = [\"チョキ\", \"パー\", \"グー\"]\nwins = 0\nfor i in range(3):\n    result = judge(my_hands[i], cpu_hands[i])\n    print(f\"{i+1}回目: {my_hands[i]} vs {cpu_hands[i]} → {result}\")\n    if result == \"勝ち\": wins += 1\nprint(f\"勝利数: {wins}/3\")",hints:["for i in range(3):","my_hands[i]とcpu_hands[i]を使う","judge(my_hands[i], cpu_hands[i])"]}}
]},

// ========== 14. Pythonで電卓を作ろう ==========
{id:"py-calc",title:"Pythonで電卓を作ろう",desc:"四則演算の関数作成からエラーハンドリングまで、実用的な電卓を完成させよう",level:"s",icon:"🔢",free:true,nextCourse:"py-data-auto",lessons:[
{id:"ca1",title:"四則演算の関数",xp:60,
content:[{type:"text",body:"## 電卓を作ろう - まずは四則演算！🔢\n\nこのコースでは**実用的な電卓プログラム**を段階的に作っていくよ。\n\nまずは基本の4つの計算を関数にしよう：\n\n| 計算 | 関数名 | 例 |\n|---|---|---|\n| 足し算 | `add(a, b)` | `add(3, 5)` → 8 |\n| 引き算 | `sub(a, b)` | `sub(10, 3)` → 7 |\n| 掛け算 | `mul(a, b)` | `mul(4, 5)` → 20 |\n| 割り算 | `div(a, b)` | `div(10, 3)` → 3.33... |"},{type:"code",code:"def add(a, b): return a + b\ndef sub(a, b): return a - b\ndef mul(a, b): return a * b\ndef div(a, b): return a / b\n\nprint(add(10, 3))   # → 13\nprint(div(10, 3))   # → 3.333...",desc:"1行で書ける短い関数。return で値を返す"},{type:"text",body:"### なぜ関数にする？\n\n`print(10 + 3)` で済む計算をわざわざ関数にする理由：\n\n1. **再利用**: 何度でも呼び出せる\n2. **組み合わせ**: `add(mul(2, 3), 4)` → (2×3)+4 = 10\n3. **拡張**: あとからログ機能やエラー処理を**関数の中だけ**で追加できる\n\n「小さな部品を組み合わせる」のがプログラミングの本質！"},{type:"tip",body:"💡 `div(10, 3)` の結果が `3.3333333333333335` になるのは浮動小数点の仕様。整数で割りたいなら `//`（切り捨て除算）を使おう。"}],exercise:{instruction:"4つの関数を定義し(10,3)で呼び出し。",initialCode:"# 4つの計算関数\n",expectedOutput:"13\n7\n30\n3.3333333333333335",keywords:["def","return","print"],answer:"def add(a, b): return a + b\ndef sub(a, b): return a - b\ndef mul(a, b): return a * b\ndef div(a, b): return a / b\nprint(add(10, 3))\nprint(sub(10, 3))\nprint(mul(10, 3))\nprint(div(10, 3))",hints:["def add(a, b): return a + b","4つ定義して4回呼び出し"]}},
{id:"ca2",title:"計算を選択して実行",xp:70,
content:[{type:"text",body:"## 1つの関数にまとめる 🎛️\n\n4つの関数を1つの `calculate(op, a, b)` にまとめよう！\n\n使い方のイメージ：\n\n<span class=\"copyable\">calculate(\"+\", 10, 5)</span> → 15\n<span class=\"copyable\">calculate(\"*\", 3, 7)</span> → 21\n\n演算子（`\"+\"`, `\"-\"` など）を引数で受け取って、if/elifで分岐する。"},{type:"code",code:"def calculate(op, a, b):\n    if op == \"+\": return a + b\n    elif op == \"-\": return a - b\n    elif op == \"*\": return a * b\n    elif op == \"/\": return a / b\n    else: return \"不明な演算子\"\n\nprint(calculate(\"+\", 15, 3))   # → 18\nprint(calculate(\"*\", 15, 3))   # → 45",desc:"演算子を文字列で渡して、if/elif で分岐"},{type:"text",body:"### `else` で想定外に備える\n\nユーザーが `\"@\"` とか `\"abc\"` を渡すかもしれない。`else` でキャッチしておけば、プログラムが変な動きをするのを防げる。\n\n**「うまくいかないケース」を先に考える**のが堅牢なプログラムの第一歩！"},{type:"tip",body:"💡 この `calculate()` が電卓の心臓部分。次のレッスンでエラーハンドリング、その次で履歴機能を追加していくよ。少しずつ機能を足していく開発スタイルは実務でも同じ！"}],exercise:{instruction:"calculate(op,a,b)で(+,-,*,/,20,8)の4計算を表示。",initialCode:"# calculate関数\n",expectedOutput:"28\n12\n160\n2.5",keywords:["def","calculate","return","print"],answer:"def calculate(op, a, b):\n    if op == \"+\": return a + b\n    elif op == \"-\": return a - b\n    elif op == \"*\": return a * b\n    elif op == \"/\": return a / b\nprint(calculate(\"+\", 20, 8))\nprint(calculate(\"-\", 20, 8))\nprint(calculate(\"*\", 20, 8))\nprint(calculate(\"/\", 20, 8))",hints:["if op == \"+\":","4回呼び出し"]}},
{id:"ca3",title:"エラーハンドリング",xp:80,
content:[{type:"text",body:"## エラーに強い電卓に！🛡️\n\n電卓で `10 ÷ 0` を押したらどうなる？ クラッシュじゃなく「エラー: 0で割れません」と表示するべきだよね。\n\n`try/except` で**壊れない電卓**を作ろう！"},{type:"code",code:"def safe_calculate(op, a, b):\n    try:\n        if op == \"+\": return a + b\n        elif op == \"-\": return a - b\n        elif op == \"*\": return a * b\n        elif op == \"/\": return a / b\n    except ZeroDivisionError:\n        return \"エラー: 0で割れません\"\n\nprint(safe_calculate(\"/\", 10, 0))  # → エラーメッセージ\nprint(safe_calculate(\"/\", 10, 2))  # → 5.0",desc:"tryの中で0除算 → exceptにジャンプしてエラーメッセージを返す"},{type:"text",body:"### 電卓で起こりうるエラー\n\n| エラー | 原因 | 対処 |\n|---|---|---|\n| ZeroDivisionError | 0で割った | エラーメッセージを返す |\n| TypeError | 文字列を計算 | 数値に変換してリトライ |\n| ValueError | 変換できない | 入力し直しを促す |\n\nプロは「**起こりうるエラーを全部書き出す**」→「全部対処」の順で作る。"},{type:"tip",body:"💡 `except` の中で `return` するのがポイント。printで直接表示するより、結果を**返す**ことで呼び出し側が判断できる柔軟な設計になる。"}],exercise:{instruction:"safe_calculate(op,a,b)を作り、(/,10,0)と(/,10,2)をテスト。",initialCode:"# 安全な計算関数\n",expectedOutput:"エラー: 0で割れません\n5.0",keywords:["def","try","except","return"],answer:"def safe_calculate(op, a, b):\n    try:\n        if op == \"+\": return a + b\n        elif op == \"-\": return a - b\n        elif op == \"*\": return a * b\n        elif op == \"/\": return a / b\n    except ZeroDivisionError:\n        return \"エラー: 0で割れません\"\nprint(safe_calculate(\"/\", 10, 0))\nprint(safe_calculate(\"/\", 10, 2))",hints:["try:の中に計算","except ZeroDivisionError:"]}},
{id:"ca4",title:"計算履歴をリストで管理",xp:90,
content:[{type:"text",body:"## 計算履歴を追加！📜\n\n電卓に**履歴機能**をつけよう。計算するたびにリストに記録して、あとから一覧表示。\n\nこの「データをリストで管理する」パターンは、チャットアプリのメッセージ履歴やToDoリストなど、**実務で超よく使う**。"},{type:"code",code:"history = []  # 空リストで初期化\n\ndef calc_with_history(op, a, b):\n    if op == \"+\": result = a + b\n    elif op == \"-\": result = a - b\n    elif op == \"*\": result = a * b\n    elif op == \"/\": result = a / b\n    history.append(f\"{a} {op} {b} = {result}\")\n    return result\n\ncalc_with_history(\"+\", 5, 3)\ncalc_with_history(\"*\", 4, 6)\nprint(\"=== 計算履歴 ===\")\nfor h in history: print(h)",desc:"append()で計算結果をどんどん追加していく"},{type:"text",body:"### ポイント\n\n- `history` はグローバル変数（関数の外で定義）\n- `history.append(...)` でリストに追加（中身を変更するだけなのでOK）\n- 関数の中で `history = []` と書くとエラーになる（再代入になるため）\n\n本格的にやるなら**クラス**でまとめるとキレイになる。OOPで学んだことの応用だね！"},{type:"tip",body:"💡 次のステップ: 「履歴の最新5件だけ表示」「履歴クリア機能」「ファイルに保存」などを追加すると、さらに実用的な電卓に。余裕があったら挑戦してみて！"}],exercise:{instruction:"3計算後に履歴表示。",initialCode:"history = []\n",expectedOutput:"=== 計算履歴 ===\n5 + 3 = 8\n4 * 6 = 24\n10 - 2 = 8",keywords:["def","append","history","print"],answer:"history = []\ndef calc_with_history(op, a, b):\n    if op == \"+\": result = a + b\n    elif op == \"-\": result = a - b\n    elif op == \"*\": result = a * b\n    elif op == \"/\": result = a / b\n    history.append(f\"{a} {op} {b} = {result}\")\n    return result\ncalc_with_history(\"+\", 5, 3)\ncalc_with_history(\"*\", 4, 6)\ncalc_with_history(\"-\", 10, 2)\nprint(\"=== 計算履歴 ===\")\nfor h in history: print(h)",hints:["history.append(...)","3回呼び出し後にfor h in history:"]}}
]},

// ========== 15. データ自動集計 ==========
{id:"py-data-auto",title:"データ自動集計",desc:"CSVデータの解析・集計・カテゴリ別分析。実務で使えるデータ処理を学ぼう",level:"i",icon:"📊",free:true,nextCourse:"shortcut-master",lessons:[
{id:"da1",title:"CSVデータをリストに変換",xp:80,
content:[{type:"text",body:"## CSVデータを扱おう！📊\n\n**CSV** = カンマで区切られたテキストデータ。Excelのデータはだいたいこの形式で書き出せる。\n\n```\n品名,個数,単価\nりんご,5,120\nバナナ,8,80\n```\n\nPythonでは `split()` で分解してリストとして扱える！\n\n### 処理の流れ\n1. `split(\"\\n\")` で改行ごとに行に分割\n2. `rows[1:]` でヘッダ（1行目）をスキップ\n3. `split(\",\")` で各行をカンマで列に分割"},{type:"code",code:"csv_data = \"品名,個数,単価\\nりんご,5,120\\nバナナ,8,80\"\n\nrows = csv_data.split(\"\\n\")    # 改行で分割\nfor row in rows[1:]:            # ヘッダをスキップ\n    cols = row.split(\",\")       # カンマで分割\n    print(f\"{cols[0]}: {cols[1]}個\")",desc:"split()で2段階に分解: 改行→行、カンマ→列"},{type:"tip",body:"💡 `cols[1]` で取り出した値は**文字列**。計算に使うなら `int(cols[1])` で数値に変換しよう。「数字に見えるけど文字列」はPython初心者がハマる落とし穴！"}],exercise:{instruction:"品名と個数を「○○: △個」で表示。",initialCode:"csv_data = \"品名,個数,単価\\nりんご,5,120\\nバナナ,8,80\\nみかん,12,60\"\n",expectedOutput:"りんご: 5個\nバナナ: 8個\nみかん: 12個",keywords:["split","for","print"],answer:"csv_data = \"品名,個数,単価\\nりんご,5,120\\nバナナ,8,80\\nみかん,12,60\"\nrows = csv_data.split(\"\\n\")\nfor row in rows[1:]:\n    cols = row.split(\",\")\n    print(f\"{cols[0]}: {cols[1]}個\")",hints:["split(\"\\n\")で行分割","rows[1:]でヘッダスキップ"]}},
{id:"da2",title:"合計・平均・最大・最小",xp:90,
content:[{type:"text",body:"## データを集計しよう！📈\n\nPythonにはデータ集計の便利関数が揃ってる：\n\n| 関数 | 何する？ | 例 |\n|---|---|---|\n| `sum()` | 合計 | `sum([1,2,3])` → 6 |\n| `len()` | 個数 | `len([1,2,3])` → 3 |\n| `max()` | 最大値 | `max([1,2,3])` → 3 |\n| `min()` | 最小値 | `min([1,2,3])` → 1 |\n\n平均は `sum() / len()` で計算！"},{type:"code",code:"def summarize(name, data):\n    print(f\"--- {name} ---\")\n    print(f\"合計: {sum(data)}\")\n    print(f\"平均: {sum(data)/len(data)}\")\n    print(f\"最大: {max(data)}\")\n    print(f\"最小: {min(data)}\")\n\nsummarize(\"テスト\", [85, 92, 68, 78, 95])",desc:"関数にまとめれば、どんなデータでも同じフォーマットで集計できる"},{type:"text",body:"### 集計関数を作るメリット\n\n売上データ、テストの点数、気温…引数を変えるだけで同じフォーマットで集計できる。DRY原則の実践！"},{type:"tip",body:"💡 空のリストを渡すと `ZeroDivisionError`（len=0で割り算）になる。実務では `if not data: return` のようにガード節を入れておこう。"}],exercise:{instruction:"summarize関数でsales集計。",initialCode:"sales = [12000, 34000, 28000, 51000, 19000]\n",expectedOutput:"--- 月間売上 ---\n合計: 144000\n平均: 28800.0\n最大: 51000\n最小: 12000",keywords:["def","sum","max","min","print"],answer:"def summarize(name, data):\n    print(f\"--- {name} ---\")\n    print(f\"合計: {sum(data)}\")\n    print(f\"平均: {sum(data)/len(data)}\")\n    print(f\"最大: {max(data)}\")\n    print(f\"最小: {min(data)}\")\nsales = [12000, 34000, 28000, 51000, 19000]\nsummarize(\"月間売上\", sales)",hints:["def summarize(name, data):","sum(), max(), min()"]}},
{id:"da3",title:"カテゴリ別に集計",xp:100,
content:[{type:"text",body:"## カテゴリ別に集計！🏷️\n\n「店舗別の売上合計」「商品別の販売数」みたいに、カテゴリごとにまとめたいことって多いよね。\n\nやり方は：**辞書にカテゴリ名をキー、値のリストをバリューとして貯める**。\n\n### 処理の流れ\n1. 空の辞書 `{}` を用意\n2. データをループ。キーがなければ空リストで初期化\n3. 値を `append()` で追加\n4. 最後に各カテゴリの `sum()` を計算"},{type:"code",code:"sales = [(\"A店\",100),(\"B店\",200),(\"A店\",150),(\"B店\",300)]\n\nshops = {}  # 空の辞書\nfor shop, val in sales:\n    if shop not in shops:\n        shops[shop] = []   # 新しいキーなら空リスト\n    shops[shop].append(val)\n\nfor shop, vals in shops.items():\n    print(f\"{shop}: 合計{sum(vals)}円\")",desc:"辞書 + append パターン。データ集約の超定番！"},{type:"tip",body:"💡 この「辞書 + append」パターンはPythonで最もよく使うデータ集約法。もっと短く書きたいなら `from collections import defaultdict` → `shops = defaultdict(list)` で初期化チェックが不要になるよ。"}],exercise:{instruction:"店舗別に合計を表示。",initialCode:"sales = [(\"A店\",100),(\"B店\",200),(\"A店\",150),(\"B店\",300),(\"A店\",250)]\n",expectedOutput:"A店: 合計500円\nB店: 合計500円",keywords:["for","if","print","sum"],answer:"sales = [(\"A店\",100),(\"B店\",200),(\"A店\",150),(\"B店\",300),(\"A店\",250)]\nshops = {}\nfor shop, val in sales:\n    if shop not in shops: shops[shop] = []\n    shops[shop].append(val)\nfor shop, vals in shops.items():\n    print(f\"{shop}: 合計{sum(vals)}円\")",hints:["辞書で管理","if shop not in shops:"]}},
{id:"da4",title:"結果をフォーマットして表示",xp:100,
content:[{type:"text",body:"## データを見やすく表示！📋\n\n集計したら、見やすく表示することも大事。f文字列の**幅指定**を使うとテキストの表が作れる。\n\n| 書式 | 意味 | 結果 |\n|---|---|---|\n| `{x:<10}` | 10幅で左寄せ | `\"hello     \"` |\n| `{x:>10}` | 10幅で右寄せ | `\"     hello\"` |\n\n数字は右寄せ、文字は左寄せが一般的。\n\n**注意**: 日本語は全角文字なので、Pythonの幅指定とは見た目がずれることがあるよ。"},{type:"code",code:"items = {\"商品A\": 4500, \"商品B\": 3200, \"商品C\": 7800}\n\nprint(f\"{'品名':<6}{'売上':>8}\")\nprint(\"-\" * 14)\nfor name, val in items.items():\n    print(f\"{name:<6}{val:>8}\")\nprint(\"-\" * 14)\nprint(f\"{'合計':<6}{sum(items.values()):>8}\")",desc:"<6で左寄せ6幅、>8で右寄せ8幅。\"-\"*14で区切り線"},{type:"tip",body:"💡 `{val:>8,}` のように `,` をつけると**桁区切り**（1,500のように）になる。大きい数字が見やすくなるテクニック！"}],exercise:{instruction:"売上レポートを表組みで表示。\n品名(<6)と売上(>8)の幅指定、区切り線(\"-\"*14)、合計行を含めてください。",initialCode:"items = {\"商品A\": 4500, \"商品B\": 3200, \"商品C\": 7800}\n",expectedOutput:"品名          売上\n--------------\n商品A       4500\n商品B       3200\n商品C       7800\n--------------\n合計       15500",keywords:["for","print","sum"],answer:"items = {\"商品A\": 4500, \"商品B\": 3200, \"商品C\": 7800}\nprint(f\"{'品名':<6}{'売上':>8}\")\nprint(\"-\" * 14)\nfor name, val in items.items():\n    print(f\"{name:<6}{val:>8}\")\nprint(\"-\" * 14)\nprint(f\"{'合計':<6}{sum(items.values()):>8}\")",hints:["f\"{name:<6}{val:>8}\"で幅指定","\"-\" * 14 で区切り線","sum(items.values())で合計"]}}
]}
];