// PyMasters v3 - Course Data
const COURSES = [
// ========== 1. Pythonをはじめよう ==========
{id:"py-start",title:"Pythonをはじめよう",desc:"プログラミングの世界へ最初の一歩。何も知らなくて大丈夫！",level:"b",icon:"🌱",free:true,nextCourse:"py-basics",lessons:[
{id:"s1",title:"プログラミングって何？",xp:30,
content:[
{type:"text",body:"## プログラミングって何だろう？\n\nプログラミングとは、**コンピュータへの指示書を書くこと**です。\n\n身近な例で考えてみましょう。料理のレシピを思い浮かべてください。\n\n「①卵を割る → ②フライパンで焼く → ③お皿に盛る」\n\nこのように、**やることを順番に書き出す**のがプログラミングです。コンピュータは人間と違って、曖昧な指示では動けません。「いい感じに焼いて」ではダメで、「中火で3分焼く」のように**具体的に**伝える必要があります。"},
{type:"text",body:"### なぜPythonなの？\n\nプログラミング言語はたくさんありますが、Pythonは**世界で最も人気のある言語のひとつ**です。\n\n人気の理由:\n- **読みやすい**: 英語に近い書き方で、初心者でも理解しやすい\n- **なんでもできる**: Webサイト、AI、データ分析、ゲーム開発…\n- **仲間が多い**: 困ったとき、ネットで日本語の情報がたくさん見つかる"},
{type:"tip",body:"💡 **安心してください！** このアプリでは、何かをインストールする必要はありません。ブラウザの中でPythonが動くので、右のエディタにコードを書いて、すぐに試せます！"}
],exercise:{instruction:"右のエディタに以下のコードを書いて、Enterキーで実行してみましょう！\nprint(\"プログラミング、楽しそう！\")",initialCode:"# ここにコードを書いてね！\n",expectedOutput:"プログラミング、楽しそう！",keywords:["print"],answer:'print("プログラミング、楽しそう！")',hints:["print() という命令を使います","カッコの中に表示したい文字を書きます","print(\"プログラミング、楽しそう！\") と書いてみてください"]}},

{id:"s2",title:"画面に文字を表示しよう - print文",xp:40,
content:[
{type:"text",body:"## <span class=\"term\" data-term=\"print\">print文</span>を覚えよう\n\n<span class=\"term\" data-term=\"print\">print()</span>は、カッコの中に書いたものを画面に表示する命令です。\n\nプログラミングで最初に覚える、一番大切な命令です。\n\n### 書き方のルール\n\n文字を表示するには、**ダブルクォート( \" )** か **シングルクォート( ' )** で囲みます。\n\nどちらでもOKですが、統一するのがコツです。\n\n<span class=\"copyable\">print(\"こんにちは\")</span>\n\n<span class=\"copyable\">print('こんにちは')</span>\n\nどちらも同じ結果になります。"},
{type:"code",code:"print(\"こんにちは！\")\nprint('Pythonへようこそ')\nprint(42)\nprint(3.14)",desc:"文字列はクォートで囲む。数字はクォート不要！"},
{type:"text",body:"### 数字はクォートなし\n\n数字を表示するときは、クォートで囲まなくてOKです。\n\n<span class=\"copyable\">print(100)</span> → 数字の100\n\n<span class=\"copyable\">print(\"100\")</span> → 文字としての100\n\n今は同じに見えますが、後で計算をするときに大きな違いが出ます！"},
{type:"tip",body:"💡 **よくあるミス**: print のスペルを間違えたり、カッコ () を忘れたりすることがあります。エラーが出たら、まずスペルとカッコを確認しましょう！"}
],exercise:{instruction:"3行で表示してください。\n1行目: 「Python」\n2行目: 「は」\n3行目: 「楽しい！」",initialCode:"# 3つのprint文を書いてね\n",expectedOutput:"Python\nは\n楽しい！",keywords:["print"],answer:"print(\"Python\")\nprint(\"は\")\nprint(\"楽しい！\")",hints:["print() を3回書きます","1つのprint()で1行表示されます","print(\"Python\")\\nprint(\"は\")\\nprint(\"楽しい！\")"]}},

{id:"s3",title:"計算もできる！",xp:40,
content:[
{type:"text",body:"## Pythonは超高性能な電卓\n\nPythonでは、<span class=\"term\" data-term=\"print\">print()</span>の中で計算もできます。\n\n<span class=\"copyable\">print(10 + 3)</span> → 13\n\n<span class=\"copyable\">print(100 - 25)</span> → 75\n\n<span class=\"copyable\">print(6 * 7)</span> → 42（掛け算は `*` を使います）\n\n<span class=\"copyable\">print(10 / 3)</span> → 3.3333...（割り算は `/`）"},
{type:"code",code:"print(10 + 3)\nprint(100 - 25)\nprint(6 * 7)\nprint(10 / 3)",desc:"足し算(+)、引き算(-)、掛け算(*)、割り算(/)"},
{type:"text",body:"### 文字と計算を混ぜる\n\n文字と数字を一緒に表示したい場合は、あとで学ぶ「f文字列」を使いますが、今はまず計算だけ試してみましょう。"},
{type:"tip",body:"💡 **掛け算は ×ではなく * （アスタリスク）** を使います。キーボードのShift+8で入力できます。割り算は ÷ ではなく / （スラッシュ）です。"}
],exercise:{instruction:"1980円の商品に消費税10%を足した合計金額を計算して表示してください。\nヒント: 1980 + 1980 * 0.1 または 1980 * 1.1",initialCode:"# 税込価格を計算して表示！\n",expectedOutput:"2178.0",keywords:["print","1980"],answer:"print(1980 * 1.1)",hints:["print() の中に計算式を書きます","1980 * 1.1 で税込価格が出ます","print(1980 * 1.1) と書いてみてください"]}}
]},

// ========== 2. Python基礎マスター ==========
{id:"py-basics",title:"Python基礎マスター",desc:"変数・データ型・文字列・計算。Pythonの土台をしっかり固めよう",level:"b",icon:"🐣",free:true,nextCourse:"py-control",lessons:[
{id:"b1",title:"変数 - データに名前をつける箱",xp:50,
content:[
{type:"text",body:"## <span class=\"term\" data-term=\"variable\">変数</span>とは？\n\n<span class=\"term\" data-term=\"variable\">変数</span>は、データを入れておく**名前つきの箱**です。\n\n想像してみてください。引っ越しのとき、段ボール箱に「食器」「本」「服」とラベルを貼りますよね。プログラミングの<span class=\"term\" data-term=\"variable\">変数</span>もまったく同じです。\n\nデータに名前をつけて保存し、あとから名前で取り出せます。\n\n### 書き方\n\n<span class=\"copyable\">name = \"太郎\"</span>\n\nこれは「nameという箱に、太郎という文字列を入れる」という意味です。`=` は「等しい」ではなく**「代入する（入れる）」**という意味です。"},
{type:"code",code:"name = \"太郎\"\nage = 20\nprint(name)\nprint(age)\n\n# 箱の中身は変えられる\nage = 21\nprint(age)",desc:"= で代入。中身はいつでも変更可能"},
{type:"text",body:"### 命名ルール\n\n- 英字、数字、`_`（アンダースコア）が使える\n- 数字で始めるのはNG（`1name` はダメ）\n- 大文字小文字は区別される（`Name` と `name` は別の箱）\n- <span class=\"term\" data-term=\"variable\">変数</span>名は**中身がわかる名前**にするのがコツ！"},
{type:"tip",body:"💡 `x = 25` より <span class=\"copyable\">age = 25</span> の方が「あ、年齢だな」とわかりますよね。プロのプログラマーは変数名にとてもこだわります！"}
],exercise:{instruction:"変数 fruit に \"りんご\" を代入し、変数 price に 150 を代入して、それぞれ表示してください。",initialCode:"# 変数を定義して表示しよう\n",expectedOutput:"りんご\n150",keywords:["fruit","price","print"],answer:"fruit = \"りんご\"\nprice = 150\nprint(fruit)\nprint(price)",hints:["fruit = \"りんご\" で変数に文字列を代入","price = 150 で数字を代入（クォートなし）","print(fruit) と print(price) で表示"]}},

{id:"b2",title:"データの種類 - データ型",xp:50,
content:[
{type:"text",body:"## <span class=\"term\" data-term=\"data-type\">データ型</span>って何？\n\nPythonのデータには「種類（型）」があります。\n\n日常生活でも、数字と文字は違うものですよね。「3 + 5」は計算できますが、「りんご + みかん」は計算できません。\n\nPythonも同じで、データの型によってできることが変わります。\n\n| 型の名前 | 何のデータ？ | 書き方の例 |\n|---|---|---|\n| <span class=\"term\" data-term=\"int\">int</span> | 整数（小数点なし） | `42`, `-10`, `0` |\n| <span class=\"term\" data-term=\"float\">float</span> | 小数（小数点あり） | `3.14`, `-0.5` |\n| <span class=\"term\" data-term=\"str\">str</span> | 文字列 | `\"Hello\"`, `'abc'` |\n| <span class=\"term\" data-term=\"bool\">bool</span> | 真偽値（はい/いいえ） | `True`, `False` |"},
{type:"code",code:"x = 10          # int（整数）\ny = 3.14        # float（小数）\nname = \"Python\" # str（文字列）\nis_fun = True   # bool（真偽値）\n\nprint(type(x))\nprint(type(y))\nprint(type(name))\nprint(type(is_fun))",desc:"type() で変数の型を確認できる"},
{type:"tip",body:"💡 <span class=\"copyable\">type()</span> は「この箱の中身はどんな種類？」と聞く命令です。デバッグで大活躍します！"}
],exercise:{instruction:"変数 a に 42 を、変数 b に 3.14 を、変数 c に \"Hello\" を代入し、それぞれのtype()を表示してください。",initialCode:"# 3つの変数を定義してtype()で確認\n",expectedOutput:"<class 'int'>\n<class 'float'>\n<class 'str'>",keywords:["type","print"],answer:"a = 42\nb = 3.14\nc = \"Hello\"\nprint(type(a))\nprint(type(b))\nprint(type(c))",hints:["a = 42 で整数を代入","type(a) で型を取得","print(type(a)) で型を表示"]}},

{id:"b3",title:"文字列を自在に操ろう",xp:60,
content:[
{type:"text",body:"## 文字列の結合と<span class=\"term\" data-term=\"f-string\">f文字列</span>\n\n文字列は `+` でつなげられます。\n\n<span class=\"copyable\">\"Hello\" + \" World\"</span> → `\"Hello World\"`\n\nでも、もっと便利なのが<span class=\"term\" data-term=\"f-string\">f文字列</span>（エフ文字列）です。\n\n文字列の前に `f` をつけて、`{}` の中に<span class=\"term\" data-term=\"variable\">変数</span>を入れるだけ！\n\n<span class=\"copyable\">f\"{name}さん、こんにちは！\"</span>"},
{type:"code",code:"name = \"太郎\"\nage = 20\n\n# f文字列（超便利！）\nprint(f\"{name}さんは{age}歳です\")\n\n# 文字列メソッド\nmsg = \"hello python\"\nprint(msg.upper())    # 全部大文字\nprint(msg.title())    # 先頭だけ大文字\nprint(len(msg))       # 文字数",desc:"f文字列と便利な文字列メソッド"},
{type:"tip",body:"💡 <span class=\"term\" data-term=\"f-string\">f文字列</span>はPython3.6以降の機能で、現在最もよく使われる文字列フォーマット方法です。`f` を忘れずに！"}
],exercise:{instruction:"変数 item に \"コーヒー\"、変数 price に 350 を代入し、f文字列で「コーヒーは350円です」と表示してください。",initialCode:"# f文字列で表示しよう\n",expectedOutput:"コーヒーは350円です",keywords:["print","f\""],answer:"item = \"コーヒー\"\nprice = 350\nprint(f\"{item}は{price}円です\")",hints:["item = \"コーヒー\" で文字列代入","f\"...\" でf文字列を作る","print(f\"{item}は{price}円です\")"]}},

{id:"b4",title:"Pythonで計算しよう - 演算子",xp:60,
content:[
{type:"text",body:"## <span class=\"term\" data-term=\"operator\">演算子</span>の一覧\n\n| <span class=\"term\" data-term=\"operator\">演算子</span> | 意味 | 例 | 結果 |\n|---|---|---|---|\n| `+` | 足し算 | `10 + 3` | 13 |\n| `-` | 引き算 | `10 - 3` | 7 |\n| `*` | 掛け算 | `10 * 3` | 30 |\n| `/` | 割り算 | `10 / 3` | 3.33... |\n| `//` | 切り捨て割り算 | `10 // 3` | 3 |\n| `%` | 余り | `10 % 3` | 1 |\n| `**` | べき乗 | `2 ** 3` | 8 |\n\n`//` と `%` は特に便利です。割り勘計算で「1人いくら？余りは？」という計算ができます。"},
{type:"code",code:"# 割り勘計算\ntotal = 5000\npeople = 3\nper_person = total // people  # 1人分（切り捨て）\namari = total % people        # 余り\nprint(f\"1人 {per_person}円（余り{amari}円）\")",desc:"実用例: 割り勘計算"},
{type:"tip",body:"💡 `%`（余り）を使うと「偶数か奇数か」を判定できます。<span class=\"copyable\">number % 2 == 0</span> なら偶数です！"}
],exercise:{instruction:"3人で4200円の食事を割り勘します。1人分（//で切り捨て）と余りを計算し「1人1400円（余り0円）」と表示してください。",initialCode:"# 割り勘を計算\n",expectedOutput:"1人1400円（余り0円）",keywords:["//","%","print"],answer:"total = 4200\npeople = 3\nprint(f\"1人{total // people}円（余り{total % people}円）\")",hints:["total // people で1人分","total % people で余り","f文字列で1つのprintにまとめる"]}},

{id:"b5",title:"型変換 - データの変身",xp:60,
content:[
{type:"text",body:"## <span class=\"term\" data-term=\"type-conversion\">型変換</span>\n\n文字列の `\"50\"` と数字の `50` は別物です。\n\n`\"50\" + \"30\"` → `\"5030\"`（文字列の結合！計算にならない！）\n\n`50 + 30` → `80`（数字の計算）\n\nデータの型を変えることを<span class=\"term\" data-term=\"type-conversion\">型変換</span>と言います。\n\n| 変換 | 関数 | 例 |\n|---|---|---|\n| 整数に | <span class=\"copyable\">int()</span> | `int(\"50\")` → `50` |\n| 小数に | <span class=\"copyable\">float()</span> | `float(\"3.14\")` → `3.14` |\n| 文字列に | <span class=\"copyable\">str()</span> | `str(100)` → `\"100\"` |"},
{type:"code",code:"# 文字列 → 数字\na = \"50\"\nb = \"30\"\nprint(a + b)          # 文字列の結合: 5030\nprint(int(a) + int(b))  # 数字の計算: 80\n\n# 数字 → 文字列\nage = 20\nprint(\"私は\" + str(age) + \"歳\")",desc:"型変換で文字と数字を行き来"},
{type:"tip",body:"💡 ユーザー入力は常に文字列です。計算したいときは必ず <span class=\"copyable\">int()</span> や <span class=\"copyable\">float()</span> で変換しましょう！"}
],exercise:{instruction:"変数 a に文字列 \"80\"、変数 b に文字列 \"20\" を代入し、int()で整数に変換してから足し算した結果を表示してください。",initialCode:"# 文字列を数字に変換して計算\n",expectedOutput:"100",keywords:["int","print"],answer:"a = \"80\"\nb = \"20\"\nprint(int(a) + int(b))",hints:["a = \"80\" で文字列として定義","int(a) で整数に変換","print(int(a) + int(b))"]}}
]},

// ========== 3. 条件分岐とループ ==========
{id:"py-control",title:"条件分岐とループ",desc:"if文・for文・while文で、プログラムに判断と繰り返しをさせよう",level:"b",icon:"🔀",free:true,nextCourse:"py-func",lessons:[
{id:"c1",title:"もし〜なら - if文の基本",xp:60,
content:[
{type:"text",body:"## <span class=\"term\" data-term=\"if\">if文</span>（条件分岐）\n\n日常生活でも「もし雨なら傘を持つ」と判断しますよね。プログラムにも同じ判断をさせられます。\n\n```python\nif 条件:\n    実行する処理\n```\n\n**超重要**: 条件の後ろにコロン `:` をつけて、次の行は**スペース4つ分右にずらす**（<span class=\"term\" data-term=\"indent\">インデント</span>）。この<span class=\"term\" data-term=\"indent\">インデント</span>がPythonの特徴で、「この処理はifの中ですよ」という意味になります。"},
{type:"code",code:"age = 20\n\nif age >= 18:\n    print(\"成人です\")\n\nif age < 18:\n    print(\"未成年です\")",desc:">=は「以上」、<は「より小さい」"},
{type:"text",body:"### <span class=\"term\" data-term=\"comparison\">比較演算子</span>\n\n| 演算子 | 意味 | 例 |\n|---|---|---|\n| `==` | 等しい | `x == 5` |\n| `!=` | 等しくない | `x != 5` |\n| `>` | より大きい | `x > 5` |\n| `<` | より小さい | `x < 5` |\n| `>=` | 以上 | `x >= 5` |\n| `<=` | 以下 | `x <= 5` |\n\n⚠️ `=` は<span class=\"term\" data-term=\"assignment\">代入</span>、`==` は比較です。混同注意！"},
{type:"tip",body:"💡 <span class=\"term\" data-term=\"indent\">インデント</span>は**スペース4つ**が標準です。Tabキーを押すと自動で入ります。インデントがずれるとエラーになるので注意！"}
],exercise:{instruction:"変数 score に 85 を代入し、80以上なら「合格！」と表示してください。",initialCode:"# スコアで合格判定\n",expectedOutput:"合格！",keywords:["if","print","score"],answer:"score = 85\nif score >= 80:\n    print(\"合格！\")",hints:["score = 85 で定義","if score >= 80: で条件判定","print(\"合格！\") をインデントして書く"]}},

{id:"c2",title:"もっと条件を - elif と else",xp:60,
content:[
{type:"text",body:"## <span class=\"term\" data-term=\"elif\">elif</span>と<span class=\"term\" data-term=\"else\">else</span>\n\n「もしAなら→Bなら→それ以外なら」と複数の条件を書けます。\n\n```python\nif 条件1:\n    処理1\nelif 条件2:\n    処理2\nelse:\n    それ以外の処理\n```\n\n<span class=\"term\" data-term=\"elif\">elif</span>は「else if」の略です。条件をいくつでも追加できます。"},
{type:"code",code:"score = 75\n\nif score >= 90:\n    print(\"Sランク\")\nelif score >= 80:\n    print(\"Aランク\")\nelif score >= 70:\n    print(\"Bランク\")\nelse:\n    print(\"Cランク\")",desc:"成績ランク判定の例"},
{type:"tip",body:"💡 条件は**上から順番に**チェックされます。最初にTrueになった条件だけが実行され、残りはスキップされます。"}
],exercise:{instruction:"変数 age に 17 を代入し、18以上なら「成人です」、そうでなければ「未成年です」と表示してください。",initialCode:"# 年齢判定\n",expectedOutput:"未成年です",keywords:["if","else","print"],answer:"age = 17\nif age >= 18:\n    print(\"成人です\")\nelse:\n    print(\"未成年です\")",hints:["age = 17 で定義","if age >= 18: で18歳以上チェック","else: で「それ以外」を処理"]}},

{id:"c3",title:"繰り返し① - for文",xp:60,
content:[
{type:"text",body:"## <span class=\"term\" data-term=\"for\">for文</span>\n\n同じ処理を何度も繰り返したいとき、<span class=\"term\" data-term=\"for\">for文</span>を使います。\n\n```python\nfor 変数 in 繰り返すもの:\n    処理\n```\n\n<span class=\"term\" data-term=\"range\">range()</span>と組み合わせると、指定回数だけ繰り返せます。\n\n<span class=\"copyable\">range(5)</span> → 0, 1, 2, 3, 4 の5回\n<span class=\"copyable\">range(1, 6)</span> → 1, 2, 3, 4, 5\n<span class=\"copyable\">range(0, 10, 2)</span> → 0, 2, 4, 6, 8（2つ飛ばし）"},
{type:"code",code:"# 5回繰り返し\nfor i in range(5):\n    print(f\"{i}番目\")\n\nprint(\"---\")\n\n# リストの繰り返し\nfruits = [\"りんご\", \"バナナ\", \"みかん\"]\nfor f in fruits:\n    print(f\"{f}が好き！\")",desc:"range()とリストでの繰り返し"},
{type:"tip",body:"💡 <span class=\"term\" data-term=\"range\">range(5)</span> は0から始まって4で終わります（5は含まない！）。1から始めたいなら <span class=\"copyable\">range(1, 6)</span> と書きます。"}
],exercise:{instruction:"for文を使って、1から5までの数字を1行ずつ表示してください。",initialCode:"# 1から5まで表示\n",expectedOutput:"1\n2\n3\n4\n5",keywords:["for","range","print"],answer:"for i in range(1, 6):\n    print(i)",hints:["range(1, 6) で1~5の範囲","for i in range(1, 6): でループ","print(i) で数字を表示"]}},

{id:"c4",title:"繰り返し② - while文",xp:70,
content:[
{type:"text",body:"## <span class=\"term\" data-term=\"while\">while文</span>\n\n<span class=\"term\" data-term=\"condition\">条件</span>がTrueの間、ずっと繰り返します。\n\n```python\nwhile 条件:\n    処理\n```\n\nfor文が「〇回繰り返す」なら、while文は「条件を満たす間ずっと繰り返す」です。\n\n⚠️ 条件がずっとTrueだと**無限ループ**になるので注意！必ず条件が変わるようにしましょう。\n\n<span class=\"term\" data-term=\"break\">break</span>: ループを途中で抜ける\n<span class=\"term\" data-term=\"continue\">continue</span>: 今回だけスキップして次へ"},
{type:"code",code:"count = 5\nwhile count > 0:\n    print(count)\n    count -= 1  # countを1減らす\nprint(\"発射！\")",desc:"カウントダウン"},
{type:"tip",body:"💡 `count -= 1` は `count = count - 1` の省略形です。`+=` や `*=` もあります！"}
],exercise:{instruction:"while文で n=1 から始めて、n<=5 の間 n を表示し、最後に「完了」と表示してください。",initialCode:"# while文で1~5表示\n",expectedOutput:"1\n2\n3\n4\n5\n完了",keywords:["while","print"],answer:"n = 1\nwhile n <= 5:\n    print(n)\n    n += 1\nprint(\"完了\")",hints:["n = 1 で初期化","while n <= 5: で条件","print(n) の後に n += 1 を忘れずに"]}},

{id:"c5",title:"条件の組み合わせ - and, or, not",xp:70,
content:[
{type:"text",body:"## <span class=\"term\" data-term=\"logical\">論理演算子</span>\n\n複数の条件を組み合わせられます。\n\n| 演算子 | 意味 | 例 |\n|---|---|---|\n| `and` | 両方True | 「晴れ **and** 休み」→ 両方満たすとき |\n| `or` | どちらかTrue | 「土曜 **or** 日曜」→ どちらかでOK |\n| `not` | 反転 | 「**not** 雨」→ 雨じゃないとき |"},
{type:"code",code:"age = 25\nhas_ticket = True\n\nif age >= 18 and has_ticket:\n    print(\"入場できます\")\nelse:\n    print(\"入場できません\")",desc:"2つの条件を and で組み合わせ"},
{type:"tip",body:"💡 `and` は「かつ（両方満たす）」、`or` は「または（どちらか）」です。日常語に置き換えると理解しやすい！"}
],exercise:{instruction:"score=75, attendance=True。「score>=60 かつ attendance==True」なら「合格」、そうでなければ「不合格」と表示。",initialCode:"# 合格判定\n",expectedOutput:"合格",keywords:["and","if","print"],answer:"score = 75\nattendance = True\nif score >= 60 and attendance:\n    print(\"合格\")\nelse:\n    print(\"不合格\")",hints:["score = 75, attendance = True","if score >= 60 and attendance:","条件を満たすので「合格」"]}}
]},

// ========== 4. 関数をマスター ==========
{id:"py-func",title:"関数をマスター",desc:"コードを整理して再利用。def・引数・戻り値を学ぼう",level:"b",icon:"⚡",free:true,nextCourse:"py-ds",lessons:[
{id:"f1",title:"関数って何？ - 料理レシピのように",xp:70,
content:[
{type:"text",body:"## <span class=\"term\" data-term=\"function\">関数</span>とは？\n\n<span class=\"term\" data-term=\"function\">関数</span>は「処理のレシピ」です。\n\n料理で例えると：「カレーの作り方」をレシピに書いておけば、何度でもそのレシピ通りに作れますよね。プログラミングの<span class=\"term\" data-term=\"function\">関数</span>も同じで、処理をまとめて名前をつけ、何度でも呼び出せます。\n\n```python\ndef 関数名(引数):\n    処理\n    return 戻り値\n```\n\n<span class=\"term\" data-term=\"def\">def</span> は「define（定義する）」の略です。"},
{type:"code",code:"def greet(name):\n    return f\"こんにちは、{name}さん！\"\n\nprint(greet(\"太郎\"))\nprint(greet(\"花子\"))",desc:"関数の定義と呼び出し"},
{type:"tip",body:"💡 <span class=\"term\" data-term=\"function\">関数</span>を使うと、同じコードを何度も書かなくて済みます。プロは「2回以上書くならら関数にする」を意識しています！"}
],exercise:{instruction:"引数 a と b の合計を返す関数 add を作り、add(3, 7) の結果を表示してください。",initialCode:"# add関数を定義\n",expectedOutput:"10",keywords:["def","return","print"],answer:"def add(a, b):\n    return a + b\nprint(add(3, 7))",hints:["def add(a, b): で定義","return a + b で合計を返す","print(add(3, 7)) で表示"]}},

{id:"f2",title:"引数と戻り値",xp:70,
content:[
{type:"text",body:"## <span class=\"term\" data-term=\"argument\">引数</span>と<span class=\"term\" data-term=\"return\">戻り値</span>\n\n<span class=\"term\" data-term=\"function\">関数</span>を自動販売機に例えると:\n\n- **<span class=\"term\" data-term=\"argument\">引数</span>** = 入れるお金とボタン（INPUT）\n- **処理** = 中でジュースを出す仕組み\n- **<span class=\"term\" data-term=\"return\">戻り値</span>** = 出てくるジュース（OUTPUT）\n\n<span class=\"term\" data-term=\"return\">return</span>がないと `None` が返ります。"},
{type:"code",code:"def calc_tax(price):\n    \"\"\"税込価格を計算する\"\"\"\n    return int(price * 1.1)\n\nresult = calc_tax(1000)\nprint(f\"税込: {result}円\")\nprint(f\"税込: {calc_tax(2500)}円\")",desc:"戻り値を変数に入れたり、直接printしたり"},
{type:"tip",body:"💡 `\"\"\"...\"\"\"`は<span class=\"term\" data-term=\"docstring\">ドキュメント文字列</span>（docstring）と言い、関数の説明を書くための特別なコメントです。"}
],exercise:{instruction:"価格を受け取り、10%割引後の価格を返す関数 discount を作り、discount(1000) の結果を表示してください。",initialCode:"# 割引関数\n",expectedOutput:"900",keywords:["def","return","print"],answer:"def discount(price):\n    return int(price * 0.9)\nprint(discount(1000))",hints:["def discount(price): で定義","price * 0.9 で10%割引","return int(...) で整数にして返す"]}},

{id:"f3",title:"デフォルト引数",xp:70,
content:[
{type:"text",body:"## <span class=\"term\" data-term=\"default-arg\">デフォルト引数</span>\n\n<span class=\"term\" data-term=\"argument\">引数</span>に初期値を設定できます。呼び出し時に省略すると初期値が使われます。\n\n<span class=\"copyable\">def greet(name, greeting=\"こんにちは\"):</span>\n\nこのように書くと、greeting を省略したら「こんにちは」が使われます。"},
{type:"code",code:"def greet(name, greeting=\"こんにちは\"):\n    print(f\"{greeting}、{name}さん！\")\n\ngreet(\"太郎\")\ngreet(\"花子\", \"おはよう\")",desc:"デフォルト引数で省略可能に"},
{type:"tip",body:"💡 <span class=\"term\" data-term=\"default-arg\">デフォルト引数</span>は、API設計で「省略可能なオプション」を作るときに大活躍します！"}
],exercise:{instruction:"greet(name, greeting=\"こんにちは\") を定義し、greet(\"太郎\") と greet(\"花子\", \"おはよう\") を呼び出してください。",initialCode:"# デフォルト引数付き関数\n",expectedOutput:"こんにちは、太郎さん！\nおはよう、花子さん！",keywords:["def","print"],answer:"def greet(name, greeting=\"こんにちは\"):\n    print(f\"{greeting}、{name}さん！\")\ngreet(\"太郎\")\ngreet(\"花子\", \"おはよう\")",hints:["def greet(name, greeting=\"こんにちは\"):","print(f\"{greeting}、{name}さん！\")","greet を2回呼び出す"]}},

{id:"f4",title:"ラムダ式 - 1行で関数を",xp:80,
content:[
{type:"text",body:"## <span class=\"term\" data-term=\"lambda\">ラムダ式</span>\n\n1行で書ける短い<span class=\"term\" data-term=\"function\">関数</span>です。\n\n```python\nlambda 引数: 戻り値の式\n```\n\n通常の関数:\n```python\ndef double(x):\n    return x * 2\n```\n\n<span class=\"term\" data-term=\"lambda\">ラムダ式</span>:\n<span class=\"copyable\">double = lambda x: x * 2</span>"},
{type:"code",code:"square = lambda x: x ** 2\nprint(square(5))\nprint(square(8))\n\n# sorted()でよく使う\ndata = [(\"B\", 2), (\"A\", 1), (\"C\", 3)]\nsorted_data = sorted(data, key=lambda x: x[1])\nprint(sorted_data)",desc:"ラムダ式の基本とsorted()での使用例"},
{type:"tip",body:"💡 <span class=\"term\" data-term=\"lambda\">ラムダ式</span>は `sorted()` や `filter()` と組み合わせるのが定番。データ処理で大活躍します！"}
],exercise:{instruction:"ラムダ式で引数を3倍する関数 triple を定義し、triple(7) の結果を表示してください。",initialCode:"# ラムダ式\n",expectedOutput:"21",keywords:["lambda","print"],answer:"triple = lambda x: x * 3\nprint(triple(7))",hints:["lambda x: x * 3","triple = lambda x: x * 3","print(triple(7))"]}}
]},

// ========== 5. データ構造 ==========
{id:"py-ds",title:"データ構造",desc:"リスト・辞書・タプル・リスト内包表記でデータを効率管理",level:"i",icon:"📦",free:true,nextCourse:"py-clean",lessons:[
{id:"d1",title:"リスト - データの列",xp:80,content:[{type:"text",body:"## <span class=\"term\" data-term=\"list\">リスト</span>\n\n<span class=\"term\" data-term=\"list\">リスト</span>は、複数のデータを**順番に並べて**保存するデータ構造です。\n\n<span class=\"copyable\">fruits = [\"りんご\", \"バナナ\", \"みかん\"]</span>\n\n<span class=\"term\" data-term=\"index\">インデックス</span>（番号）は **0から** 始まります。"},{type:"code",code:"fruits = [\"りんご\", \"バナナ\", \"みかん\"]\nprint(fruits[0])\nfruits.append(\"ぶどう\")\nprint(len(fruits))\nprint(fruits)",desc:"リストの作成・アクセス・追加"},{type:"text",body:"### よく使う<span class=\"term\" data-term=\"method\">メソッド</span>\n\n- <span class=\"copyable\">.append(x)</span> 末尾に追加\n- <span class=\"copyable\">.sort()</span> ソート\n- <span class=\"copyable\">.pop()</span> 末尾を取り出し\n- <span class=\"copyable\">len(list)</span> 要素数"}],exercise:{instruction:"[3, 1, 4, 1, 5] をsort()でソートして表示してください。",initialCode:"# ソートして表示\n",expectedOutput:"[1, 1, 3, 4, 5]",keywords:["sort","print"],answer:"numbers = [3, 1, 4, 1, 5]\nnumbers.sort()\nprint(numbers)",hints:["numbers = [3, 1, 4, 1, 5]","numbers.sort() でソート","print(numbers)"]}},
{id:"d2",title:"辞書 - 名前でデータを引く",xp:80,content:[{type:"text",body:"## <span class=\"term\" data-term=\"dict\">辞書</span>（dict）\n\n<span class=\"term\" data-term=\"dict\">辞書</span>は**キーと値のペア**でデータを管理します。\n\n<span class=\"copyable\">user = {\"name\": \"太郎\", \"age\": 25}</span>"},{type:"code",code:"user = {\"name\": \"太郎\", \"age\": 25, \"city\": \"東京\"}\nprint(user[\"name\"])\nuser[\"email\"] = \"taro@example.com\"\n\nfor key, value in user.items():\n    print(f\"{key}: {value}\")",desc:"辞書の作成・アクセス・追加・ループ"},{type:"tip",body:"💡 <span class=\"term\" data-term=\"dict\">辞書</span>はJSON（Web APIのデータ形式）そのものです。Web開発では毎日使います！"}],exercise:{instruction:"商品辞書を作成。\"name\":\"ノートPC\", \"price\":98000。f文字列で「ノートPC: 98000円」と表示。",initialCode:"# 商品辞書\n",expectedOutput:"ノートPC: 98000円",keywords:["print"],answer:"item = {\"name\": \"ノートPC\", \"price\": 98000}\nprint(f\"{item['name']}: {item['price']}円\")",hints:["item = {\"name\": \"ノートPC\", \"price\": 98000}","item[\"name\"] でアクセス","f文字列でまとめて表示"]}},
{id:"d3",title:"タプルとセット",xp:80,content:[{type:"text",body:"## <span class=\"term\" data-term=\"tuple\">タプル</span>と<span class=\"term\" data-term=\"set\">セット</span>\n\nタプルは変更できないリスト。セットは重複なしの集合。"},{type:"code",code:"coords = (10, 20)\nprint(coords[0])\n\nnumbers = [1, 2, 3, 2, 1, 3, 4]\nunique = set(numbers)\nprint(unique)\nprint(len(unique))",desc:"タプルとセットの基本"}],exercise:{instruction:"リスト [1, 2, 2, 3, 3, 3, 4] からset()で重複を除き、要素数をlen()で表示してください。",initialCode:"# 重複を除く\n",expectedOutput:"4",keywords:["set","len","print"],answer:"data = [1, 2, 2, 3, 3, 3, 4]\nprint(len(set(data)))",hints:["set() でセットに変換","len() で要素数","print(len(set(data)))"]}},
{id:"d4",title:"リスト内包表記",xp:90,content:[{type:"text",body:"## <span class=\"term\" data-term=\"list-comp\">リスト内包表記</span>\n\nPythonの強力機能。リストを1行で作れます。\n\n<span class=\"copyable\">[式 for 変数 in イテラブル if 条件]</span>"},{type:"code",code:"squares = [i ** 2 for i in range(1, 6)]\nprint(squares)\n\nevens = [i for i in range(10) if i % 2 == 0]\nprint(evens)",desc:"リスト内包表記の例"},{type:"tip",body:"💡 Pythonらしい書き方の代表格。コードが短くなり処理速度も速い！"}],exercise:{instruction:"リスト内包表記で1~10の奇数リストを作り表示してください。",initialCode:"# 奇数リスト\n",expectedOutput:"[1, 3, 5, 7, 9]",keywords:["for","if"],answer:"odds = [i for i in range(1, 11) if i % 2 != 0]\nprint(odds)",hints:["range(1, 11) で1~10","i % 2 != 0 で奇数判定","[i for i in range(1, 11) if i % 2 != 0]"]}}
]},

// ========== 6. きれいなコードの書き方 ==========
{id:"py-clean",title:"きれいなコードの書き方",desc:"コメント・命名規則・コードの整理。読みやすいコードを書こう",level:"i",icon:"✨",free:true,nextCourse:"py-error",lessons:[
{id:"cl1",title:"コメント - 未来の自分へのメモ",xp:50,content:[{type:"text",body:"## <span class=\"term\" data-term=\"comment\">コメント</span>\n\n`#` の後に書いた文字はプログラムに無視されます。コメントは「未来の自分」への手紙です。"},{type:"code",code:"# 消費税率（2024年時点）\nTAX_RATE = 0.1\n\ndef calc_total(price):\n    \"\"\"税込価格を計算する\"\"\"\n    return int(price * (1 + TAX_RATE))\n\nprint(calc_total(1000))",desc:"実践的なコメントの書き方"}],exercise:{instruction:"以下のコードにコメントを追加して実行してください。\n1行目の上に # で「1~5の2乗リストを作成」というコメントを書いてください。",initialCode:"# ここにコメントを書いてね\nresult = [i ** 2 for i in range(1, 6)]\nprint(result)",expectedOutput:"[1, 4, 9, 16, 25]",keywords:["#","print"],answer:"# 1~5の2乗リストを作成\nresult = [i ** 2 for i in range(1, 6)]\nprint(result)",hints:["# でコメントを書く","コードの上に説明を書く","# 1~5の2乗リストを作成"]}},
{id:"cl2",title:"変数名のつけ方",xp:50,content:[{type:"text",body:"## 命名規則 - PEP8\n\n| 種類 | 書き方 | 例 |\n|---|---|---|\n| 変数名 | snake_case | `user_name` |\n| 関数名 | snake_case | `calc_tax()` |\n| 定数 | UPPER_CASE | `MAX_COUNT` |"},{type:"code",code:"# ✅ 良い例\nuser_age = 25\ndef add_numbers(num1, num2):\n    return num1 + num2\nprint(add_numbers(3, 7))",desc:"読みやすい名前"}],exercise:{instruction:"変数名をわかりやすく書き換えて同じ結果を出してください。\nx = 1000\ny = 0.1\nprint(int(x + x * y))",initialCode:"# 変数名をわかりやすく！\n",expectedOutput:"1100",keywords:["print"],answer:"price = 1000\ntax_rate = 0.1\nprint(int(price + price * tax_rate))",hints:["x は何？→ price","y は何？→ tax_rate","名前を変えるだけ"]}},
{id:"cl3",title:"関数で整理整頓 - DRY原則",xp:60,content:[{type:"text",body:"## DRY原則\n\nDon't Repeat Yourself。繰り返すコードは関数にまとめる！"},{type:"code",code:"def show_price(name, price):\n    print(f\"{name}: {int(price * 1.1)}円\")\n\nshow_price(\"りんご\", 100)\nshow_price(\"バナナ\", 200)\nshow_price(\"みかん\", 150)",desc:"関数で重複コードを排除"}],exercise:{instruction:"show_score(name, score) を作り3人分呼び出してください。",initialCode:"# show_score関数を作ろう\n",expectedOutput:"太郎: 85点\n花子: 92点\n次郎: 78点",keywords:["def","print"],answer:"def show_score(name, score):\n    print(f\"{name}: {score}点\")\nshow_score(\"太郎\", 85)\nshow_score(\"花子\", 92)\nshow_score(\"次郎\", 78)",hints:["def show_score(name, score):","print(f\"{name}: {score}点\")","3回呼び出す"]}}
]},

// ========== 7. オブジェクト指向入門 ==========
{id:"py-oop",title:"オブジェクト指向入門",desc:"クラスと継承。現実世界をコードで表現しよう",level:"i",icon:"🏗️",free:true,nextCourse:"py-janken",lessons:[
{id:"o1",title:"クラスとは？",xp:100,content:[{type:"text",body:"## クラス\n\nクラスは「設計図」、インスタンスは「設計図から作った実物」です。"},{type:"code",code:"class Dog:\n    def __init__(self, name, age):\n        self.name = name\n        self.age = age\n    def bark(self):\n        return f\"{self.name}「ワン！」\"\n\ndog1 = Dog(\"ポチ\", 3)\nprint(dog1.bark())",desc:"クラス定義→インスタンス作成"}],exercise:{instruction:"Catクラスを作成。describe()で「ミケ は 三毛 色です」と返す。",initialCode:"# Catクラス\n",expectedOutput:"ミケ は 三毛 色です",keywords:["class","def","self"],answer:"class Cat:\n    def __init__(self, name, color):\n        self.name = name\n        self.color = color\n    def describe(self):\n        return f\"{self.name} は {self.color} 色です\"\nprint(Cat(\"ミケ\", \"三毛\").describe())",hints:["class Cat: で定義","__init__ で name, color を保存","describe で f文字列を返す"]}},
{id:"o2",title:"メソッドを使いこなそう",xp:100,content:[{type:"text",body:"## メソッド\n\nクラスの中に定義した関数をメソッドと呼びます。"},{type:"code",code:"class Counter:\n    def __init__(self):\n        self.count = 0\n    def add(self):\n        self.count += 1\n    def show(self):\n        print(f\"カウント: {self.count}\")\n\nc = Counter()\nc.add()\nc.add()\nc.add()\nc.show()",desc:"カウンターをクラスで実装"}],exercise:{instruction:"BankAccountクラス。初期残高0、deposit(amount)で入金、show()で残高表示。1000円入金。",initialCode:"# BankAccount\n",expectedOutput:"残高: 1000円",keywords:["class","def","self"],answer:"class BankAccount:\n    def __init__(self):\n        self.balance = 0\n    def deposit(self, amount):\n        self.balance += amount\n    def show(self):\n        print(f\"残高: {self.balance}円\")\nacc = BankAccount()\nacc.deposit(1000)\nacc.show()",hints:["__init__ で self.balance = 0","deposit で self.balance += amount","show で残高を表示"]}},
{id:"o3",title:"継承",xp:110,content:[{type:"text",body:"## 継承\n\n既存のクラスを拡張して新しいクラスを作れます。"},{type:"code",code:"class Animal:\n    def __init__(self, name):\n        self.name = name\n\nclass Dog(Animal):\n    def speak(self):\n        return f\"{self.name}「ワン！」\"\n\nclass Cat(Animal):\n    def speak(self):\n        return f\"{self.name}「ニャー！」\"\n\nfor a in [Dog(\"ポチ\"), Cat(\"タマ\")]:\n    print(a.speak())",desc:"親クラスを継承して子クラスを作る"}],exercise:{instruction:"Shape(name)、Circle(name, radius)を作り、area()で面積(3.14*r**2)を返す。",initialCode:"# Shape, Circle\n",expectedOutput:"円\n78.5",keywords:["class","def"],answer:"class Shape:\n    def __init__(self, name):\n        self.name = name\nclass Circle(Shape):\n    def __init__(self, name, radius):\n        super().__init__(name)\n        self.radius = radius\n    def area(self):\n        return 3.14 * self.radius ** 2\nc = Circle(\"円\", 5)\nprint(c.name)\nprint(c.area())",hints:["class Circle(Shape): で継承","super().__init__(name)","3.14 * self.radius ** 2"]}}
]},

// ========== 8. エラーと友達になろう ==========
{id:"py-error",title:"エラーと友達になろう",desc:"エラーメッセージの読み方・try/except・デバッグのコツ",level:"i",icon:"🛡️",free:true,nextCourse:"py-oop",lessons:[
{id:"e1",title:"エラーメッセージを読もう",xp:80,content:[{type:"text",body:"## エラーは怖くない！\n\nプロでも毎日エラーを出します。大事なのはエラーメッセージを読むこと。"},{type:"code",code:"name = \"太郎\"\nage = 25\nprint(\"年齢: \" + str(age))\nprint(f\"年齢: {age}\")",desc:"TypeErrorの例と対処法"}],exercise:{instruction:"文字列 \"100\" と数字 50 を足して 150 を表示してください。",initialCode:"# 型変換でエラーを避ける\n",expectedOutput:"150",keywords:["int","print"],answer:"a = \"100\"\nprint(int(a) + 50)",hints:["\"100\" は文字列","int() で変換","print(int(\"100\") + 50)"]}},
{id:"e2",title:"try/except",xp:90,content:[{type:"text",body:"## try/except\n\nエラーが起きそうなコードを安全に実行できます。"},{type:"code",code:"def safe_divide(a, b):\n    try:\n        return a / b\n    except ZeroDivisionError:\n        return \"0では割れません\"\n\nprint(safe_divide(10, 3))\nprint(safe_divide(10, 0))",desc:"0除算エラーをキャッチ"}],exercise:{instruction:"[\"10\",\"abc\",\"30\"]をループし、int()変換できた数字の合計を表示。",initialCode:"# 合計を求める\n",expectedOutput:"40",keywords:["try","except","print"],answer:"total = 0\nfor item in [\"10\", \"abc\", \"30\"]:\n    try:\n        total += int(item)\n    except ValueError:\n        pass\nprint(total)",hints:["total = 0 で初期化","try: total += int(item)","except ValueError: pass"]}},
{id:"e3",title:"デバッグのコツ",xp:90,content:[{type:"text",body:"## デバッグの基本\n\n1. print文デバッグ 2. エラーメッセージを読む 3. 小さく試す"},{type:"code",code:"def calculate_average(scores):\n    total = sum(scores)\n    count = len(scores)\n    return total / count\n\nresult = calculate_average([80, 90, 70])\nprint(f\"平均: {result}\")",desc:"print文デバッグの例"}],exercise:{instruction:"リスト [10, 20, 30, 40, 50] の平均値を計算して表示。",initialCode:"# 平均値を計算\n",expectedOutput:"30.0",keywords:["sum","len","print"],answer:"scores = [10, 20, 30, 40, 50]\naverage = sum(scores) / len(scores)\nprint(average)",hints:["sum() で合計","len() で要素数","合計÷要素数=平均"]}}
]},

// ========== 9. エディタショートカット マスター ==========
{id:"shortcut-master",title:"エディタショートカット マスター",desc:"VS Code (Windows) の必須ショートカットで作業効率10倍",level:"s",icon:"⌨️",free:true,lessons:[
{id:"sc1",title:"保存・元に戻す・やり直し",xp:40,content:[{type:"text",body:"## まず覚える3つ\n\n| 操作 | ショートカット |\n|---|---|\n| 保存 | Ctrl+S |\n| 元に戻す | Ctrl+Z |\n| やり直し | Ctrl+Y |"}],exercise:{instruction:"変数 shortcut に \"Ctrl+S\" を代入し「保存: Ctrl+S」と表示。",initialCode:"# ショートカット\n",expectedOutput:"保存: Ctrl+S",keywords:["print"],answer:"shortcut = \"Ctrl+S\"\nprint(f\"保存: {shortcut}\")",hints:["shortcut = \"Ctrl+S\"","f文字列で表示"]}},
{id:"sc2",title:"カーソル移動と選択",xp:40,content:[{type:"text",body:"## 高速カーソル移動\n\n| 操作 | ショートカット |\n|---|---|\n| 行頭へ | Home |\n| 行末へ | End |\n| 単語単位で移動 | Ctrl+←/→ |"}],exercise:{instruction:"辞書にショートカットを格納しループで表示。",initialCode:"# ショートカット辞書\n",expectedOutput:"行頭: Home\n行末: End\n単語移動: Ctrl+矢印",keywords:["for","print"],answer:"sc = {\"行頭\": \"Home\", \"行末\": \"End\", \"単語移動\": \"Ctrl+矢印\"}\nfor k, v in sc.items():\n    print(f\"{k}: {v}\")",hints:["辞書を作成","for k, v in sc.items():","print(f\"{k}: {v}\")"]}},
{id:"sc3",title:"コピー・切り取り・行操作",xp:50,content:[{type:"text",body:"## テキスト操作\n\nCtrl+C コピー / Ctrl+X 切り取り / Ctrl+V 貼り付け"}],exercise:{instruction:"リスト[\"Ctrl+C\",\"Ctrl+X\",\"Ctrl+V\"]を番号付きで表示。",initialCode:"# 番号付き表示\n",expectedOutput:"1. Ctrl+C\n2. Ctrl+X\n3. Ctrl+V",keywords:["for","enumerate","print"],answer:"keys = [\"Ctrl+C\", \"Ctrl+X\", \"Ctrl+V\"]\nfor i, k in enumerate(keys, 1):\n    print(f\"{i}. {k}\")",hints:["enumerate(list, 1)","for i, k in enumerate(...):"]}},
{id:"sc4",title:"検索・置換・マルチカーソル",xp:50,content:[{type:"text",body:"## 検索と置換\n\nCtrl+F 検索 / Ctrl+H 置換 / Ctrl+D 同じ単語選択"}],exercise:{instruction:"文字列の\"user\"を全て\"customer\"に置換して表示。",initialCode:"# 一括置換\n",expectedOutput:"customer_name, customer_age, customer_email",keywords:["replace","print"],answer:"text = \"user_name, user_age, user_email\"\nprint(text.replace(\"user\", \"customer\"))",hints:["text = \"user_name, ...\"",".replace(\"user\", \"customer\")"]}},
{id:"sc5",title:"TOP10まとめ",xp:60,content:[{type:"text",body:"## TOP 10\n\n1. Ctrl+S 2. Ctrl+Z 3. Ctrl+C/X/V 4. Ctrl+D 5. Ctrl+F 6. Ctrl+H 7. Ctrl+P 8. Ctrl+Shift+P 9. Ctrl+/ 10. Alt+↑↓"}],exercise:{instruction:"TOP10をenumerate()で表示。",initialCode:"# TOP 10\n",expectedOutput:"1. Ctrl+S - 保存\n2. Ctrl+Z - 元に戻す\n3. Ctrl+C - コピー\n4. Ctrl+X - 切り取り\n5. Ctrl+V - 貼り付け\n6. Ctrl+D - 同じ単語選択\n7. Ctrl+F - 検索\n8. Ctrl+H - 置換\n9. Ctrl+P - ファイルを開く\n10. Ctrl+/ - コメント切替",keywords:["for","enumerate","print"],answer:"top = [(\"Ctrl+S\",\"保存\"),(\"Ctrl+Z\",\"元に戻す\"),(\"Ctrl+C\",\"コピー\"),(\"Ctrl+X\",\"切り取り\"),(\"Ctrl+V\",\"貼り付け\"),(\"Ctrl+D\",\"同じ単語選択\"),(\"Ctrl+F\",\"検索\"),(\"Ctrl+H\",\"置換\"),(\"Ctrl+P\",\"ファイルを開く\"),(\"Ctrl+/\",\"コメント切替\")]\nfor i,(k,d) in enumerate(top,1):\n    print(f\"{i}. {k} - {d}\")",hints:["タプルのリストを作成","enumerate(top, 1)"]}}
]},

// ========== 10. ミニゲーム (PRO) ==========
{id:"py-game",title:"Pythonでミニゲーム作り",desc:"じゃんけん・数当て・クイズ。楽しみながら実力アップ",level:"i",icon:"🎮",free:false,lessons:[
{id:"g1",title:"じゃんけんゲーム",xp:100,content:[{type:"text",body:"## じゃんけんゲーム\n\nrandomモジュールでランダムな手を出させます。"},{type:"code",code:"import random\nhands = [\"グー\", \"チョキ\", \"パー\"]\nplayer = \"グー\"\ncomputer = random.choice(hands)\nprint(f\"あなた: {player}\")\nprint(f\"PC: {computer}\")",desc:"じゃんけんゲーム"}],exercise:{instruction:"random.choice()で色を選んで表示。",initialCode:"import random\n",expectedOutput:"",keywords:["random.choice","print"],answer:"import random\ncolor = random.choice([\"赤\", \"青\", \"緑\"])\nprint(color)",hints:["random.choice([...])","print(color)"]}},
{id:"g2",title:"数当てゲーム",xp:110,content:[{type:"text",body:"## 数当てゲーム"},{type:"code",code:"import random\nanswer = random.randint(1, 10)\nguess = 5\nif guess == answer:\n    print(\"正解！\")\nelse:\n    print(f\"答えは{answer}でした\")",desc:"数当てゲーム"}],exercise:{instruction:"random.randint(1,10)で数字を生成し表示。",initialCode:"import random\n",expectedOutput:"",keywords:["random.randint","print"],answer:"import random\nnum = random.randint(1, 10)\nprint(f\"答えは{num}です\")",hints:["random.randint(1, 10)"]}},
{id:"g3",title:"クイズアプリ",xp:120,content:[{type:"text",body:"## クイズアプリ"},{type:"code",code:"quizzes = [\n    {\"q\": \"Pythonの作者は？\", \"a\": \"グイド\"},\n    {\"q\": \"print()は何をする？\", \"a\": \"表示\"},\n]\nscore = 0\nfor quiz in quizzes:\n    score += 1\nprint(f\"スコア: {score}/{len(quizzes)}\")",desc:"クイズ"}],exercise:{instruction:"3問のクイズスコアを表示。",initialCode:"# クイズ\n",expectedOutput:"3問中3問正解！",keywords:["for","print"],answer:"quizzes = [{\"q\":\"1+1=\",\"a\":2},{\"q\":\"2*3=\",\"a\":6},{\"q\":\"10//3=\",\"a\":3}]\nscore = 0\nfor q in quizzes:\n    score += 1\nprint(f\"{len(quizzes)}問中{score}問正解！\")",hints:["辞書リスト","forでループ"]}}
]},

// ========== 11. Webスクレイピング (PRO) ==========
{id:"py-scraping",title:"Webスクレイピング入門",desc:"Webからデータを自動取得する基礎を学ぼう",level:"a",icon:"🌐",free:false,lessons:[
{id:"w1",title:"HTMLの基本",xp:100,content:[{type:"text",body:"## HTMLとは？\n\nWebページはHTMLで書かれています。"},{type:"code",code:"html = '<h1>PyMasters</h1>'\ntitle_start = html.find('<h1>') + 4\ntitle_end = html.find('</h1>')\nprint(html[title_start:title_end])",desc:"HTMLからデータ取り出し"}],exercise:{instruction:"<title>PyMasters</title>からタイトルを取り出して表示。",initialCode:"html = '<title>PyMasters</title>'\n",expectedOutput:"PyMasters",keywords:["find","print"],answer:"html = '<title>PyMasters</title>'\nstart = html.find('<title>') + 7\nend = html.find('</title>')\nprint(html[start:end])",hints:["find()で位置を探す","スライスで切り出す"]}},
{id:"w2",title:"データ取得の仕組み",xp:110,content:[{type:"text",body:"## requestsライブラリ\n\nHTTPステータスコードの概念を学びましょう。"},{type:"code",code:"status_code = 200\nif status_code == 200:\n    print(\"ページ取得成功！\")",desc:"HTTPステータスコード"}],exercise:{instruction:"status=404で判定。404なら「ページが見つかりません」。",initialCode:"# ステータスコード判定\n",expectedOutput:"ページが見つかりません",keywords:["if","elif","print"],answer:"status = 404\nif status == 200:\n    print(\"成功\")\nelif status == 404:\n    print(\"ページが見つかりません\")\nelse:\n    print(\"エラー\")",hints:["if status == 200:","elif status == 404:"]}},
{id:"w3",title:"データを抽出しよう",xp:120,content:[{type:"text",body:"## データ抽出"},{type:"code",code:"html_items = [\n    '<li>りんご 100円</li>',\n    '<li>バナナ 200円</li>',\n]\nfor item in html_items:\n    start = item.find('>') + 1\n    end = item.find('</li>')\n    print(item[start:end])",desc:"複数アイテムから抽出"}],exercise:{instruction:"['<p>Hello</p>','<p>World</p>','<p>Python</p>']からテキストを抽出。",initialCode:"html_items = ['<p>Hello</p>', '<p>World</p>', '<p>Python</p>']\n",expectedOutput:"Hello\nWorld\nPython",keywords:["for","print"],answer:"html_items = ['<p>Hello</p>', '<p>World</p>', '<p>Python</p>']\nfor item in html_items:\n    start = item.find('>') + 1\n    end = item.find('</p>')\n    print(item[start:end])",hints:["find('>') + 1","find('</p>')"]}}
]},

// ========== 12. Python自動化 (PRO) ==========
{id:"py-auto",title:"Python自動化入門",desc:"ファイル操作・テキスト処理・レポート生成を自動化",level:"a",icon:"🤖",free:false,lessons:[
{id:"a1",title:"テキスト処理の基本",xp:100,content:[{type:"text",body:"## テキスト処理\n\nsplit()で分割、join()で結合。"},{type:"code",code:"csv_line = \"太郎,25,東京\"\nparts = csv_line.split(\",\")\nprint(f\"名前: {parts[0]}\")",desc:"split()で分割"}],exercise:{instruction:"\"Python-Java-JavaScript\"を\"-\"で分割し各言語を表示。",initialCode:"# 分割して表示\n",expectedOutput:"Python\nJava\nJavaScript",keywords:["split","for","print"],answer:"text = \"Python-Java-JavaScript\"\nfor lang in text.split(\"-\"):\n    print(lang)",hints:["split(\"-\")","for lang in ..."]}},
{id:"a2",title:"データの集計・変換",xp:110,content:[{type:"text",body:"## データ集計"},{type:"code",code:"sales = [1200, 3400, 2800, 5100, 1900]\nprint(f\"合計: {sum(sales)}円\")\nprint(f\"平均: {sum(sales)//len(sales)}円\")",desc:"組み込み関数で集計"}],exercise:{instruction:"scores = [85, 92, 78, 95, 88] の合計、平均、最高点を表示。",initialCode:"scores = [85, 92, 78, 95, 88]\n",expectedOutput:"合計: 438\n平均: 87.6\n最高: 95",keywords:["sum","max","print"],answer:"scores = [85, 92, 78, 95, 88]\nprint(f\"合計: {sum(scores)}\")\nprint(f\"平均: {sum(scores)/len(scores)}\")\nprint(f\"最高: {max(scores)}\")",hints:["sum()","max()"]}},
{id:"a3",title:"レポート自動生成",xp:120,content:[{type:"text",body:"## レポート自動生成"},{type:"code",code:"def generate_report(title, data):\n    print(f\"=== {title} ===\")\n    print(f\"合計: {sum(data)}\")\n    print(f\"平均: {sum(data)/len(data):.1f}\")\n\ngenerate_report(\"月間売上\", [12000, 34000, 28000, 51000])",desc:"関数でレポート生成"}],exercise:{instruction:"generate_report(title, numbers)を作り呼び出し。",initialCode:"# レポート関数\n",expectedOutput:"=== テスト結果 ===\n合計: 240\n平均: 80.0",keywords:["def","print","sum"],answer:"def generate_report(title, numbers):\n    print(f\"=== {title} ===\")\n    print(f\"合計: {sum(numbers)}\")\n    print(f\"平均: {sum(numbers)/len(numbers)}\")\ngenerate_report(\"テスト結果\", [80, 90, 70])",hints:["def generate_report(title, numbers):","sum() と len()"]}}
]},

// ========== NEW: じゃんけんゲームを作ろう ==========
{id:"py-janken",title:"じゃんけんゲームを作ろう",desc:"randomモジュールとif文を組み合わせて、じゃんけんゲームを完成させよう！",level:"s",icon:"🎮",free:true,nextCourse:"py-calc",lessons:[
{id:"jk1",title:"randomモジュールの使い方",xp:60,content:[{type:"text",body:"## ランダムに選ぶ\n\n`random.choice(リスト)` でリストからランダムに1つ選べます。\n\nまずは `import random` でモジュールを読み込みましょう。\n\nゲームでは毎回違う手が出るようにしますが、まずはリストの**インデックス**で手を取り出す練習をしましょう。"},{type:"code",code:"import random\nhands = [\"グー\", \"チョキ\", \"パー\"]\n\n# インデックスで取り出し\nprint(hands[0])  # グー\nprint(hands[1])  # チョキ\nprint(hands[2])  # パー\n\n# ランダムに選ぶ（実行するたび変わる）\ncpu_hand = random.choice(hands)\nprint(f\"CPUの手: {cpu_hand}\")",desc:"random.choice()とインデックス"}],exercise:{instruction:"handsリスト [\"グー\", \"チョキ\", \"パー\"] を作り、\nrandom.choice(hands)でcpu_handに代入し、\nprint(f\"選択肢: {hands}\") と print(f\"CPUの手: {cpu_hand}\") を表示してください。\n※ 2行目はランダムなので何が出てもOK！（1行目だけで採点します）",initialCode:"import random\n",expectedOutput:"選択肢: ['グー', 'チョキ', 'パー']",keywords:["random.choice","hands","print"],answer:"import random\nhands = [\"グー\", \"チョキ\", \"パー\"]\ncpu_hand = random.choice(hands)\nprint(f\"選択肢: {hands}\")",hints:["hands = [\"グー\", \"チョキ\", \"パー\"]","random.choice(hands)でランダム選択","print(f\"選択肢: {hands}\")"]}},
{id:"jk2",title:"勝敗判定ロジック",xp:70,content:[{type:"text",body:"## 勝敗判定\n\nif/elif/elseで判定します。"},{type:"code",code:"player = \"グー\"\ncpu = \"チョキ\"\nif player == cpu:\n    print(\"あいこ！\")\nelif (player==\"グー\" and cpu==\"チョキ\") or (player==\"チョキ\" and cpu==\"パー\") or (player==\"パー\" and cpu==\"グー\"):\n    print(\"あなたの勝ち！\")\nelse:\n    print(\"あなたの負け…\")",desc:"勝敗判定"}],exercise:{instruction:"player=\"パー\", cpu=\"グー\"で勝敗判定。",initialCode:"player = \"パー\"\ncpu = \"グー\"\n",expectedOutput:"あなたの勝ち！",keywords:["if","print"],answer:"player = \"パー\"\ncpu = \"グー\"\nif player == cpu:\n    print(\"あいこ！\")\nelif (player==\"グー\" and cpu==\"チョキ\") or (player==\"チョキ\" and cpu==\"パー\") or (player==\"パー\" and cpu==\"グー\"):\n    print(\"あなたの勝ち！\")\nelse:\n    print(\"あなたの負け…\")",hints:["player == cpu であいこ","勝つパターンを or でつなぐ"]}},
{id:"jk3",title:"関数にまとめる",xp:80,content:[{type:"text",body:"## 関数化\n\njudge(player, cpu)で結果を返す。"},{type:"code",code:"def judge(player, cpu):\n    if player == cpu: return \"あいこ\"\n    elif (player==\"グー\" and cpu==\"チョキ\") or (player==\"チョキ\" and cpu==\"パー\") or (player==\"パー\" and cpu==\"グー\"): return \"勝ち\"\n    else: return \"負け\"\n\nprint(judge(\"グー\", \"チョキ\"))",desc:"関数化"}],exercise:{instruction:"judge関数でjudge(\"チョキ\",\"パー\")を表示。",initialCode:"# judge関数\n",expectedOutput:"勝ち",keywords:["def","judge","return","print"],answer:"def judge(player, cpu):\n    if player == cpu: return \"あいこ\"\n    elif (player==\"グー\" and cpu==\"チョキ\") or (player==\"チョキ\" and cpu==\"パー\") or (player==\"パー\" and cpu==\"グー\"): return \"勝ち\"\n    else: return \"負け\"\nprint(judge(\"チョキ\", \"パー\"))",hints:["def judge(player, cpu):","return で結果を返す"]}},
{id:"jk4",title:"3回勝負",xp:90,content:[{type:"text",body:"## 3回勝負\n\nfor文で3回じゃんけんし勝敗カウント。\n\n実際のゲームでは `random.choice(hands)` でCPUの手をランダムに決めますが、\nまずは結果を確認しやすいように**CPUの手を事前に決めて**ループを練習しましょう。"},{type:"code",code:"def judge(p, c):\n    if p == c: return \"あいこ\"\n    elif (p==\"グー\" and c==\"チョキ\") or (p==\"チョキ\" and c==\"パー\") or (p==\"パー\" and c==\"グー\"): return \"勝ち\"\n    else: return \"負け\"\nhands = [\"グー\", \"チョキ\", \"パー\"]\nmy_hands = [\"グー\", \"パー\", \"チョキ\"]\ncpu_hands = [\"チョキ\", \"パー\", \"グー\"]\nwins = 0\nfor i in range(3):\n    result = judge(my_hands[i], cpu_hands[i])\n    print(f\"{i+1}回目: {my_hands[i]} vs {cpu_hands[i]} → {result}\")\n    if result == \"勝ち\": wins += 1\nprint(f\"勝利数: {wins}/3\")",desc:"3回勝負"}],exercise:{instruction:"judge関数を使い3回勝負。\n自分の手: [\"グー\", \"パー\", \"チョキ\"]\nCPUの手: [\"チョキ\", \"パー\", \"グー\"]\n各回の結果と勝利数を表示。",initialCode:"def judge(p, c):\n    if p == c: return \"あいこ\"\n    elif (p==\"グー\" and c==\"チョキ\") or (p==\"チョキ\" and c==\"パー\") or (p==\"パー\" and c==\"グー\"): return \"勝ち\"\n    else: return \"負け\"\nmy_hands = [\"グー\", \"パー\", \"チョキ\"]\ncpu_hands = [\"チョキ\", \"パー\", \"グー\"]\nwins = 0\n",expectedOutput:"1回目: グー vs チョキ → 勝ち\n2回目: パー vs パー → あいこ\n3回目: チョキ vs グー → 負け\n勝利数: 1/3",keywords:["for","judge","print"],answer:"def judge(p, c):\n    if p == c: return \"あいこ\"\n    elif (p==\"グー\" and c==\"チョキ\") or (p==\"チョキ\" and c==\"パー\") or (p==\"パー\" and c==\"グー\"): return \"勝ち\"\n    else: return \"負け\"\nmy_hands = [\"グー\", \"パー\", \"チョキ\"]\ncpu_hands = [\"チョキ\", \"パー\", \"グー\"]\nwins = 0\nfor i in range(3):\n    result = judge(my_hands[i], cpu_hands[i])\n    print(f\"{i+1}回目: {my_hands[i]} vs {cpu_hands[i]} → {result}\")\n    if result == \"勝ち\": wins += 1\nprint(f\"勝利数: {wins}/3\")",hints:["for i in range(3):","my_hands[i]とcpu_hands[i]を使う","judge(my_hands[i], cpu_hands[i])"]}}
]},

// ========== NEW: Pythonで電卓を作ろう ==========
{id:"py-calc",title:"Pythonで電卓を作ろう",desc:"四則演算の関数作成からエラーハンドリングまで、実用的な電卓を完成させよう",level:"s",icon:"🔢",free:true,nextCourse:"py-data-auto",lessons:[
{id:"ca1",title:"四則演算の関数",xp:60,content:[{type:"text",body:"## 電卓の基本\n\n4つの計算関数を作ろう。"},{type:"code",code:"def add(a, b): return a + b\ndef sub(a, b): return a - b\ndef mul(a, b): return a * b\ndef div(a, b): return a / b\nprint(add(10, 5))\nprint(div(10, 5))",desc:"四則演算関数"}],exercise:{instruction:"4つの関数を定義し(10,3)で呼び出し。",initialCode:"# 4つの計算関数\n",expectedOutput:"13\n7\n30\n3.3333333333333335",keywords:["def","return","print"],answer:"def add(a, b): return a + b\ndef sub(a, b): return a - b\ndef mul(a, b): return a * b\ndef div(a, b): return a / b\nprint(add(10, 3))\nprint(sub(10, 3))\nprint(mul(10, 3))\nprint(div(10, 3))",hints:["def add(a, b): return a + b","4つ定義して4回呼び出し"]}},
{id:"ca2",title:"計算を選択して実行",xp:70,content:[{type:"text",body:"## 演算子で分岐\n\ncalculate(op, a, b)を作ろう。"},{type:"code",code:"def calculate(op, a, b):\n    if op == \"+\": return a + b\n    elif op == \"-\": return a - b\n    elif op == \"*\": return a * b\n    elif op == \"/\": return a / b\nprint(calculate(\"+\", 15, 3))",desc:"演算子で分岐"}],exercise:{instruction:"calculate(op,a,b)で(+,-,*,/,20,8)の4計算を表示。",initialCode:"# calculate関数\n",expectedOutput:"28\n12\n160\n2.5",keywords:["def","calculate","return","print"],answer:"def calculate(op, a, b):\n    if op == \"+\": return a + b\n    elif op == \"-\": return a - b\n    elif op == \"*\": return a * b\n    elif op == \"/\": return a / b\nprint(calculate(\"+\", 20, 8))\nprint(calculate(\"-\", 20, 8))\nprint(calculate(\"*\", 20, 8))\nprint(calculate(\"/\", 20, 8))",hints:["if op == \"+\":","4回呼び出し"]}},
{id:"ca3",title:"エラーハンドリング",xp:80,content:[{type:"text",body:"## ゼロ除算対策\n\ntry/exceptで安全に。"},{type:"code",code:"def safe_div(a, b):\n    try: return a / b\n    except ZeroDivisionError: return \"エラー: 0で割れません\"\nprint(safe_div(10, 0))",desc:"ゼロ除算対策"}],exercise:{instruction:"safe_calculate(op,a,b)を作り、(/,10,0)と(/,10,2)をテスト。",initialCode:"# 安全な計算関数\n",expectedOutput:"エラー: 0で割れません\n5.0",keywords:["def","try","except","return"],answer:"def safe_calculate(op, a, b):\n    try:\n        if op == \"+\": return a + b\n        elif op == \"-\": return a - b\n        elif op == \"*\": return a * b\n        elif op == \"/\": return a / b\n    except ZeroDivisionError:\n        return \"エラー: 0で割れません\"\nprint(safe_calculate(\"/\", 10, 0))\nprint(safe_calculate(\"/\", 10, 2))",hints:["try:の中に計算","except ZeroDivisionError:"]}},
{id:"ca4",title:"計算履歴をリストで管理",xp:90,content:[{type:"text",body:"## 計算履歴\n\nリストのappend()で履歴保存。"},{type:"code",code:"history = []\ndef calc_with_history(op, a, b):\n    if op == \"+\": result = a + b\n    elif op == \"*\": result = a * b\n    history.append(f\"{a} {op} {b} = {result}\")\n    return result\ncalc_with_history(\"+\", 10, 5)\nfor h in history: print(h)",desc:"計算履歴"}],exercise:{instruction:"3計算後に履歴表示。",initialCode:"history = []\n",expectedOutput:"=== 計算履歴 ===\n5 + 3 = 8\n4 * 6 = 24\n10 - 2 = 8",keywords:["def","append","history","print"],answer:"history = []\ndef calc_with_history(op, a, b):\n    if op == \"+\": result = a + b\n    elif op == \"-\": result = a - b\n    elif op == \"*\": result = a * b\n    elif op == \"/\": result = a / b\n    history.append(f\"{a} {op} {b} = {result}\")\n    return result\ncalc_with_history(\"+\", 5, 3)\ncalc_with_history(\"*\", 4, 6)\ncalc_with_history(\"-\", 10, 2)\nprint(\"=== 計算履歴 ===\")\nfor h in history: print(h)",hints:["history.append(...)","3回呼び出し後にfor h in history:"]}}
]},

// ========== NEW: データ自動集計 ==========
{id:"py-data-auto",title:"データ自動集計",desc:"CSVデータの解析・集計・カテゴリ別分析。実務で使えるデータ処理を学ぼう",level:"i",icon:"📊",free:true,nextCourse:"shortcut-master",lessons:[
{id:"da1",title:"CSVデータをリストに変換",xp:80,content:[{type:"text",body:"## データ読み込み\n\nsplit()でCSVを解析。"},{type:"code",code:"csv_data = \"名前,数学,英語\\n太郎,85,72\\n花子,92,88\"\nrows = csv_data.split(\"\\n\")\nfor row in rows[1:]:\n    cols = row.split(\",\")\n    print(f\"{cols[0]}: 数学{cols[1]}点\")",desc:"CSV解析"}],exercise:{instruction:"品名と個数を「○○: △個」で表示。",initialCode:"csv_data = \"品名,個数,単価\\nりんご,5,120\\nバナナ,8,80\\nみかん,12,60\"\n",expectedOutput:"りんご: 5個\nバナナ: 8個\nみかん: 12個",keywords:["split","for","print"],answer:"csv_data = \"品名,個数,単価\\nりんご,5,120\\nバナナ,8,80\\nみかん,12,60\"\nrows = csv_data.split(\"\\n\")\nfor row in rows[1:]:\n    cols = row.split(\",\")\n    print(f\"{cols[0]}: {cols[1]}個\")",hints:["split(\"\\n\")で行分割","rows[1:]でヘッダスキップ"]}},
{id:"da2",title:"合計・平均・最大・最小",xp:90,content:[{type:"text",body:"## 集計関数\n\nsum(), len(), max(), min()が便利。"},{type:"code",code:"def summarize(name, data):\n    print(f\"--- {name} ---\")\n    print(f\"合計: {sum(data)}\")\n    print(f\"平均: {sum(data)/len(data):.1f}\")\n    print(f\"最大: {max(data)}\")\n    print(f\"最小: {min(data)}\")\nsummarize(\"テスト\", [85, 92, 68, 78, 95])",desc:"集計関数"}],exercise:{instruction:"summarize関数でsales集計。",initialCode:"sales = [12000, 34000, 28000, 51000, 19000]\n",expectedOutput:"--- 月間売上 ---\n合計: 144000\n平均: 28800.0\n最大: 51000\n最小: 12000",keywords:["def","sum","max","min","print"],answer:"def summarize(name, data):\n    print(f\"--- {name} ---\")\n    print(f\"合計: {sum(data)}\")\n    print(f\"平均: {sum(data)/len(data)}\")\n    print(f\"最大: {max(data)}\")\n    print(f\"最小: {min(data)}\")\nsales = [12000, 34000, 28000, 51000, 19000]\nsummarize(\"月間売上\", sales)",hints:["def summarize(name, data):","sum(), max(), min()"]}},
{id:"da3",title:"カテゴリ別に集計",xp:100,content:[{type:"text",body:"## 辞書でカテゴリ集計"},{type:"code",code:"data = [(\"食品\",500),(\"日用品\",300),(\"食品\",800)]\ncategories = {}\nfor cat, val in data:\n    if cat not in categories: categories[cat] = []\n    categories[cat].append(val)\nfor cat, vals in categories.items():\n    print(f\"{cat}: 合計{sum(vals)}円\")",desc:"カテゴリ集計"}],exercise:{instruction:"店舗別に合計を表示。",initialCode:"sales = [(\"A店\",100),(\"B店\",200),(\"A店\",150),(\"B店\",300),(\"A店\",250)]\n",expectedOutput:"A店: 合計500円\nB店: 合計500円",keywords:["for","if","print","sum"],answer:"sales = [(\"A店\",100),(\"B店\",200),(\"A店\",150),(\"B店\",300),(\"A店\",250)]\nshops = {}\nfor shop, val in sales:\n    if shop not in shops: shops[shop] = []\n    shops[shop].append(val)\nfor shop, vals in shops.items():\n    print(f\"{shop}: 合計{sum(vals)}円\")",hints:["辞書で管理","if shop not in shops:"]}},
{id:"da4",title:"結果をフォーマットして表示",xp:100,content:[{type:"text",body:"## f文字列で表組み\n\n幅指定で揃えて表示。\n\n`<6` は「6文字分の幅で左寄せ」、`>8` は「8文字分の幅で右寄せ」です。\n\n**注意**: Pythonの幅指定は文字数ベースです。日本語のような全角文字も1文字としてカウントされるため、見た目の幅がずれることがあります。"},{type:"code",code:"data = {\"りんご\": 1500, \"バナナ\": 800}\nfor name, val in data.items():\n    print(f\"{name:<8}{val:>8,}\")",desc:"表組み風レポート"}],exercise:{instruction:"売上レポートを表組みで表示。\n品名(<6)と売上(>8)の幅指定、区切り線(\"-\"*14)、合計行を含めてください。",initialCode:"items = {\"商品A\": 4500, \"商品B\": 3200, \"商品C\": 7800}\n",expectedOutput:"品名          売上\n--------------\n商品A       4500\n商品B       3200\n商品C       7800\n--------------\n合計       15500",keywords:["for","print","sum"],answer:"items = {\"商品A\": 4500, \"商品B\": 3200, \"商品C\": 7800}\nprint(f\"{'品名':<6}{'売上':>8}\")\nprint(\"-\" * 14)\nfor name, val in items.items():\n    print(f\"{name:<6}{val:>8}\")\nprint(\"-\" * 14)\nprint(f\"{'合計':<6}{sum(items.values()):>8}\")",hints:["f\"{name:<6}{val:>8}\"で幅指定","\"-\" * 14 で区切り線","sum(items.values())で合計"]}}
]}
];